### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by dsvoronin** [MarathonLabs/marathon#10]
I could've add something like that: https://raw.githubusercontent.com/avito-tech/android-ui-testing/master/build.gradle.kts
but not necessarily with bintray
it will be handy to `./gradlew publishToMavenLocal / localArtifactory` for developement cycles

**Comment by dsvoronin** [comment]
Ok, seems that you already did it:

```
publishing {
   ....
    repositories {
        maven(url = "$rootDir/build/repository")
    }
}
```

i'll add a readme then

**Comment by Malinskiy** [comment]
This is actually a temporary solution only to publish for sample app. Let's setup snapshot publishing at the moment to something like MavenCentral/jCenter

**Comment by tagantroy** [comment]
#18 done
