### ISSUE TITLE
Tests with failed assumption are treated as failed tests

### ISSUE THREAD

**Issue by lukaville** [MarathonLabs/marathon#113]
For example:
```kotlin
    @Test
    fun someTest() {
        assumeTrue(false)
    }
```

![image](https://user-images.githubusercontent.com/725526/47848589-bed9ad80-ddc6-11e8-9421-eaf130cc752c.png)

This test reported as ignored when using default junit runner, but it's marked as failed when running using marathon. I think it will be better to mark it as "ignored" in marathon as well or add an option to configure this behaviour.

See https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html

**Comment by tagantroy** [comment]
Fixed #117
