### ISSUE TITLE
Video recorder is broken

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#133]
Some of the videos are broken. It looks like a problem with headers(I checked in hex editor).

**Comment by Malinskiy** [comment]
@tagantroy can you please provide a sample of the file?

**Comment by tagantroy** [comment]
Reproduced on latest develop.
[com.example.MainActivityFlakyTest#testTextFlaky3.mp4.zip](https://github.com/Malinskiy/marathon/files/2986476/com.example.MainActivityFlakyTest.testTextFlaky3.mp4.zip)


It looks like a problem with headers
