### ISSUE TITLE
Hanging tests are being returned to queue endlessly

### ISSUE THREAD

**Issue by Tieru** [MarathonLabs/marathon#142]
To reproduce this issue you can set "testOutputTimeoutMillis" to very low value. Thus your tests won't be able to complete in time and begin rescheduling forever.

This happens because after "DevicePoolMessage.FromDevice.ReturnTestBatch" message all the tests are being rescheduled again and again without taking into account retry strategy (or similar) configurations.

**Comment by Tieru** [comment]
This seems to be fixed (at least for us), although it's hard to say which changes solved this

**Comment by Malinskiy** [comment]
This is fixed by #247, you can now set a quota and completely ignore these tests. By default runner will still continue to implement the "try until succeeds/fails" behaviour for backwards compatiblity
