### ISSUE TITLE
Marathon has to continue work if influxdb isn't available

### ISSUE THREAD

**Issue by tseglevskiy** [MarathonLabs/marathon#153]
Marathon need to be more flexible in case of problem with influxdb, because main goal is to run tests, not to run it in proper order. Now in this case Marathon just fails.

**Comment by Malinskiy** [comment]
This is questionable. Influxdb is optional now so if a user chooses to use there has to be a way to indicate that it's not available.

We can implement a switch to revert back to default running in case influx is not available so every test will be treated as a new test basically. @tagantroy what do you think?

**Comment by tagantroy** [comment]
@Malinskiy +1 for fallback strategy with default values.
