### ISSUE TITLE
InfluxMetricsProvider does not update query results when parameters change

### ISSUE THREAD

**Issue by memega** [MarathonLabs/marathon#185]
After `InfluxMetricsProvider.executionTime` is called first time, query result is permanently cached and will be used in subsequent calls even with different `percentile` and `limit` values. It is problematic in current implementation because both sorting and batching strategies use the same instance of metrics provider. Sorting strategy normally initiates the first request. When batching strategy requests data later, it would be cached.

**Comment by Malinskiy** [comment]
This is fixed by @memega in his branch, let's merge it
