### ISSUE TITLE
Test crash while long initialization

### ISSUE THREAD

**Issue by xanderblinov** [MarathonLabs/marathon#193]
One of tests got really long initialization, so we got

> Test failed to run to completion. Reason: 'Failed to receive adb shell test output within 60000 ms. Test may have timed out, or adb connection to device became unresponsive'. Check device logcat for details

Any ideas or workaround how to solve this issue?

**Comment by Malinskiy** [comment]
Hey!

Did you try increasing the https://malinskiy.github.io/marathon/doc/options.html#test-output-timeout?

**Comment by xanderblinov** [comment]
Hey, we've found the class which throws exception
https://android.googlesource.com/platform/tools/base/+/master/ddmlib/src/main/java/com/android/ddmlib/testrunner/InstrumentationResultParser.java#578
Does this param exactly one what may fix this issue? 

We increased initialization data size (now it takes less then 60 sec). So, I will experiment a little bit with this param's value

**Comment by xanderblinov** [comment]
It looks like this option helps. Thank you!
