### ISSUE TITLE
Include multiple test run results into html report

### ISSUE THREAD

**Issue by lukaville** [MarathonLabs/marathon#195]
We should be able to see all test execution results for the test if it was run more than one time.

**Comment by tagantroy** [comment]
Please take a look on allure report, it is already integrated, you only need `allure generate`

**Comment by tagantroy** [comment]
@lukaville I checked on latest develop. 
test_results/raw.json also contains full information(including retries). 
<img width="587" alt="Screen Shot 2019-03-21 at 11 44 00 AM" src="https://user-images.githubusercontent.com/3902256/54732458-daefb700-4bce-11e9-84b1-0cc5d74d4d6f.png">
<img width="636" alt="Screen Shot 2019-03-21 at 11 44 04 AM" src="https://user-images.githubusercontent.com/3902256/54732459-daefb700-4bce-11e9-8cbb-c1cddde4ab3c.png">
