### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#196]
For some cases we need to fail testrun even if test finished successfully after retry, for example flaky test detection.

**Comment by tagantroy** [comment]
I see two options here:

1. Boolean flag in configuration and small customization inside TestResultReporter and PoolProgressTracker
2. Provide it as a strategy

@lukaville @Malinskiy What do you think?

**Comment by lukaville** [comment]
@tagantroy 
I don't see use cases where we can need something other than "fail if any failed"/"pass if any passed" but probably extra flexibility won't hurt
