### ISSUE TITLE
Collect performance metrics during test execution

### ISSUE THREAD

**Issue by lukaville** [MarathonLabs/marathon#213]
We can collect some useful information about test execution that can be reported to external analytics or html reports.

For example:
* Frame drops
* Java heap/native memory usage
* CPU usage

**Comment by Malinskiy** [comment]
Marathon now supports pulling random files/folders from the devices with #444
I assume this is what's needed from the runner to support this behaviour.

**Comment by lukaville** [comment]
Yes, I think this functionality is enough to collect this data. Thanks!
