### ISSUE TITLE
Add support for allure test steps

### ISSUE THREAD

**Issue by xanderblinov** [MarathonLabs/marathon#225]
Allure may create reports with test steps. It's very useful because it looks like  test cases and make error recognition better without stacktrace copypasting.

It looks like 
<img width="745" alt="Screen Shot 2019-05-08 at 17 08 31" src="https://user-images.githubusercontent.com/469876/57381632-f8470780-71b3-11e9-8d33-71bfedc51d52.png">

**Comment by Malinskiy** [comment]
This is already supported with the allure integration. Closing
