### ISSUE TITLE
Pooling Strategies

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#24]
We need define more pooling strategies. Right now we have only one strategy - common pool.
Probably we need strategy which will separate tablets and phones, run all tests on each device.
@dsvoronin @Malinskiy what do you think?

**Comment by dsvoronin** [comment]
https://github.com/gojuno/composer/pull/138#issuecomment-383300100

**Comment by Malinskiy** [comment]
We should allow segregation devices by:
- SDK version
- ABI
- Manufacturer/Model
- Screen size

We can also create something generic to create pools based on the output of **build.prop**

**Comment by cdsap** [comment]
hi, looks promising this repository!
I was checking FTL and they are adding dimensions for rotation and locale, what do you think? I  know there are companies with custom language implementations but maybe is interesting for other companies without these custom solutions.

**Comment by Malinskiy** [comment]
@cdsap why should we implement this in the runner if rotation and locale can be changed on the device using something like [test-butler](https://github.com/linkedin/test-butler)?

**Comment by cdsap** [comment]
@Malinskiy got it makes sense

**Comment by tagantroy** [comment]
#32
