### ISSUE TITLE
Logcat log from one test sometimes contains logs from several tests 

### ISSUE THREAD

**Issue by PStrelchenko** [MarathonLabs/marathon#251]
Hi! Faced with strange issue with LogCat logs. 

Platform: Android

Assume we have a lot of tests with names T1 and T2, etc. In Allure's reports we see attached LogCat logs for each of this tests. But we noticed that logs of one test sometimes contains LogCat logs from another tests. 

It is not good - it makes understanding cause of errors really a mess. 

Maybe cause of this behavior lays in `com.malinskiy.marathon.android.executor.listeners.LogCatListener`

**Comment by Malinskiy** [comment]
Hey @PStrelchenkoHH 

The logcat listener works in async fashion that is it is fired as soon as we know that test actually started.

What you describe can have multiple root causes:
- Logcat is buffer based so there might be a delay and you're seeing previous test logs
- Adb connection is laggy and even though start of the test already happened the test logs are still old
- Log reading thread might be reused on marathon side

To help you further could you please tell me more about one specific instance of this with the following info from one execution device:
- Timestamps of test executions
- Logcat logs with timestamps

at least a couple of batches of tests should be fine

**Comment by Malinskiy** [comment]
After investigation the source of the error is the asynchronous nature of logcat request: whenever we call logcat it doesn't really filter the data for a specific timeframe.

I'm trying to address this with a separate project, will update this issue when there is a solution

**Comment by Malinskiy** [comment]
This issue should be much less probable with the new vendor-adam in the develop branch.

The process of collecting the logcat log outlives the batch lifetime and is always in the background. The delay between sending command for collecting the log and actual collection is close to 0 in this case.

**Comment by Malinskiy** [comment]
@PStrelchenko would you be able to test the latest version of the marathon with adam enabled and confirm if you experience the same problem?

Thanks

**Comment by PStrelchenko** [comment]
@Malinskiy, ok, I'll try to give you feedback as soon as possible.
Thanks!

**Comment by Malinskiy** [comment]
Bump

**Comment by PStrelchenko** [comment]
Hi!
I've finally checked new Marathon with "adam" enabled, and as far as I know, there are no problems with logs anymore 👏 👏 👏 

Thanks!
