### ISSUE TITLE
Sorting Strategies

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#26]
We already implemented analytics integration(with influxdb) and we can start implementing custom sorting strategies based on this analytics.

**Comment by Malinskiy** [comment]
- N-th percentile of test execution time
- probabilty of passing

All of these should take as parameter the last X months/days/hours that need to be taken into account

**Comment by tagantroy** [comment]
> parameter the last X months/days/hours

@Malinskiy can we use retention policy instead?

**Comment by Malinskiy** [comment]
retention is different: for example I want to save metrics for the last year, but I want to check statistics only from the last 2 days, this way my tests auto-correct the execution flakiness at least in 2 days, but I can look on the data for the last year.

**Comment by tagantroy** [comment]
#32
