### ISSUE TITLE
Avoid filtering tests if testClassRegexes entry is not set in Marathonfile

### ISSUE THREAD

**Issue by alex-apriamashvili** [MarathonLabs/marathon#260]
Currently, there is a filtering logic in place to filter-out irrelevant test-cases received from the test-case parser. However, we might not need to filter any of those test-cases found at all! 
For example, all the cases found by `IOSTestParser` might be used for testing which makes that parameter redundant in some situations. However, shall the `testClassRegexes` not be specified, all the tests provided by a parser will be filtered out. 
This situation could be solved by simply specifying the following inside the *Marathonfile*:
```yml
testClassRegexes:
- "^.*$"
```
But why to specify this parameter at all if it could be avoided?

I suggest skipping the filtering step for the cases when the `testClassRegexes` is not specified in Marathonfile.

P.S: I don't mind making this change myself.

**Comment by Malinskiy** [comment]
This parameter is an optimization technique for byte-code parsers to skip some of the symbols that do not match against the regex. A runtime binary potentially contains many thousands of symbols and unless some form of sanity filtering exists it might take a long time
