### ISSUE TITLE
[iOS] Add support for multi-target configurations

### ISSUE THREAD

**Issue by alex-apriamashvili** [MarathonLabs/marathon#263]
Currently, iOS Provider doesn't have any support for multi-test-target configuration as it uses the value of a single target for all the tests. However, some projects have this kind of configuration and in that case, the list of tests gathered by the `IOSTestParser` simply becomes incorrect as it would have a single value specified for tests that are actually in a different target.
```
- TargetA/TestCaseInTargetA/testMethodInTestCaseInTargetA
- TargetA/TestCaseInTargetB/testMethodInTestCaseInTargetB
```
To support multi-target configuration an array of target needs to be introduced instead of a single value.

However, it leaves us with an open question of how to match between parsed test-cases and multiple test-targets, if there is no direct relation in there.

**Comment by Malinskiy** [comment]
@alex-apriamashvili I think it would make sense for you to stop by out slack channel :) Link in the badge on the main page [slack](https://github.com/Malinskiy/marathon)

**Comment by alex-apriamashvili** [comment]
multi-target configuration support was added in https://github.com/Malinskiy/marathon/pull/238
