### ISSUE TITLE
Retry Strategies

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#27]
[Fork](https://github.com/shazam/fork) provides very simple strategy: totalAllowedRetryQuota and retryPerTestCaseQuota. 
Should we implement same strategy? @Malinskiy @dsvoronin

**Comment by dsvoronin** [comment]
What is the point of `totalAllowedRetryQuota` between all suite?

I think `retryPerTestCaseQuota` is enough for now

**Comment by tagantroy** [comment]
maybe for case then something broken on main screen and app crashing every time on startup.

**Comment by Malinskiy** [comment]
The point is to reduce the damage in case of excessive flakiness. By damage I mean extra time spent on execution. We should do both in my opinion.

**Comment by dsvoronin** [comment]
ah i see, we handle it via execution timeout on job configuration, but this overlapping quota in maraphon makes perfect sense

**Comment by tagantroy** [comment]
#32
