### ISSUE TITLE
No video with supported format and MIME type found

### ISSUE THREAD

**Issue by hram** [MarathonLabs/marathon#276]
Hi

I have many problems with html report.
And I think all of them have common reason.
1. Instead of video I have gray box with message "No video with supported format and MIME type found"
![image](https://user-images.githubusercontent.com/2150637/66102070-be8af900-e5b9-11e9-9c4b-1904286e9f73.png)

2. Instead of screenshots I have bloken image preview
![image](https://user-images.githubusercontent.com/2150637/66102074-c480da00-e5b9-11e9-8c6e-aa7fccfbc0a0.png)

3. Instead of logs I have infinite loader
![image](https://user-images.githubusercontent.com/2150637/66102127-e5e1c600-e5b9-11e9-936c-6464e9fe85cc.png)
In browser console I have warning "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///<some path>/app/build/reports/marathon/devDebugAndroidTest/logs/omni/RODQTODETK596TLB/<some package>.ui.kakaotest.UserLoginTest%23loginSuccessWithoutSalePointTest.log. (Reason: CORS request not http)"

**Comment by Malinskiy** [comment]
There might be 2 possible issues that cause that:
1. you are not using actual http server in this case, just a local folder
2. there are no files (addressed in #324)

There is no support for server the webpages locally, please try to use the internal IDE webserver/nginx or anything else to server these files.

If the issue still persists - please reopen the ticket.
Thanks
