### ISSUE TITLE
More info in Readme

### ISSUE THREAD

**Issue by cdsap** [MarathonLabs/marathon#282]
Hi, I know the doc is here https://malinskiy.github.io/marathon/ but I think the Readme should contains some subset of information about the main features of this awesome tool. When I try to show the repo some people complains about that.

**Comment by smugleafdev** [comment]
Really hoping the gradle configuration section is added. Currently it's empty. It doesn't appear that the gradle plugin can even be configured, as far as I can tell.

**Comment by frogfx** [comment]
How to configure this in android studio

**Comment by Malinskiy** [comment]
Hey @frogfx! you can check the configuration section in the [docs](https://malinskiy.github.io/marathon/doc/downloading.html) for  CLI (preferable) or gradle plugin distribution. If in doubt - look at the [samples](https://github.com/Malinskiy/marathon/tree/develop/sample) or reach out to us on slack (there is an invite link on the README.md page).

**Comment by Malinskiy** [comment]
Updated the main readme with a basic overview
