### ISSUE TITLE
Exception during Marathon implementation: "Execution failed for JetifyTransform:"

### ISSUE THREAD

**Issue by automaticqa** [MarathonLabs/marathon#294]
I have many UI tests written in Espresso framework. And now I'm trying to implement Marathon Test Runner in my project. I added in dependency.gradle

```
ext.Versions = [
        marathon : "0.5.0",
        ...
]
ext.TestLibraries = [
    marathon : "com.malinskiy.marathon:marathon-gradle-plugin:$Versions.marathon",
    ...
]
```
then i added in all my projects gradle

`androidTestImplementation TestLibraries.marathon
`Unfortunately i get next error

```
Execution failed for task ':mobile:mergeDevDebugAndroidTestNativeLibs'.
> Could not resolve all files for configuration ':mobile:devDebugAndroidTestRuntimeClasspath'.
   > Failed to transform artifact 'common.jar (com.android.tools:common:26.3.0)' to match attributes {artifactType=android-java-res, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/.gradle/caches/modules-2/files-2.1/com.android.tools/common/26.3.0/1d9b4db75bbe5fe357c8a56db506f2361ebd508d/common-26.3.0.jar.
         > Failed to transform '/home/.gradle/caches/modules-2/files-2.1/com.android.tools/common/26.3.0/1d9b4db75bbe5fe357c8a56db506f2361ebd508d/common-26.3.0.jar' using Jetifier. Reason: The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.. (Run with --stacktrace for more details.
```
How to implement it, did i miss something?

**Comment by Malinskiy** [comment]
Hey @StanlyT, thanks for reaching out

Does your application assemble without applying marathon test runner?

The runner itself doesn't depend on espresso at all, it just expects the apk's to be available

**Comment by automaticqa** [comment]
Hey Anton, 
Yes, my app assembles without that chages in gradle. I understand that Marathon doesn't depend on Espresso. Tests' build starts crashing only if i edit dependency.gradle and build.gradle

I just think maybe i missed some setup codes for Marathon's implementation?

**Comment by Vacxe** [comment]
@StanlyT I think that you have a mistake in your gradle file.
`androidTestImplementation TestLibraries.marathon`

It's not a `androidTestImplementation`. Could you apply as a **plugin**?

**Comment by Malinskiy** [comment]
FYI https://malinskiy.github.io/marathon/doc/downloading.html#gradle

**Comment by PaladiRka** [comment]
> FYI https://malinskiy.github.io/marathon/doc/downloading.html#gradle

Link was expired
But problem is actual

**Comment by Malinskiy** [comment]
@PaladiRka The project migrated to a different org in 2 years. Please see https://marathonlabs.github.io/marathon/doc/downloading.html#gradle

**Comment by PaladiRka** [comment]
Thank you
