### ISSUE TITLE
Add support for setting serialStrategy using the Gradle Plugin

### ISSUE THREAD

**Issue by CooperRS** [MarathonLabs/marathon#298]
Heyho!

PR #231 introduced a new `serialStrategy` property to be able to explicitly choose how the serial of Android devices is derived. This is super useful in my CI environment where we create the required Android Emulator once and for each CI run start `n` read-only snapshot instances of this emulator to split up the tests.

However, I was wondering whether this `serialStrategy` can be set via the Gradle Plugin as well? I  couldn't find a matching property. Did I miss something?

Best regards,
Roland

**Comment by Malinskiy** [comment]
Hey Roland,

Thanks for reaching out! I've created #299 for this. Would you be able to test it if it's working as you expect?
