### ISSUE TITLE
Error Installing APK's

### ISSUE THREAD

**Issue by hamorillo** [MarathonLabs/marathon#300]
When I'm trying to execute marathon on an Android Project, I'm getting the following exception:

> E 22:41:43.747 [AndroidDevice - execution - emulator-5554 @coroutine#9] <AndroidAppInstaller> Error while installing es.***.app.dev.test, ***/android-***-app/app/build/outputs/apk/instrumentation/debug/***-instrumentation-debug-androidTest.apk on EMULATOR28X0X25X0
> com.android.ddmlib.InstallException: Local path doesn't exist.

The process is retried several times but it's always return the same result.

What is my error?

**Comment by Vacxe** [comment]
Firstly, could you double-check it manually? Just try to find this file in this directory

```, /android--app/app/build/outputs/apk/instrumentation/debug/-instrumentation-debug-androidTest.apk```

Also, you can try to look on the configuration 

https://malinskiy.github.io/marathon/doc/configuration.html

Especially on :
**applicationApk: 
testApplicationApk:**

I think that it can give a clue for you. Cheers!

**Comment by hamorillo** [comment]
You are right!  I had the wrong **applicationApk** property. Know I'm having other exception executing the test but I will try to solve it. 

Thank you!
