### ISSUE TITLE
The filteringConfiguration show error during execution

### ISSUE THREAD

**Issue by iammini5** [MarathonLabs/marathon#302]
Not sure if i made some mistake in the syntax, I tried to use the following in marathon file but it always show "marathon v0.5.1: Build failed "

filteringConfiguration:
  whitelist:
  - type: "fully-qualified-class-name"
    regex: "my.packagename.Test"

**Comment by Malinskiy** [comment]
Any chance you can provide the full output + stack trace with the error message @iammini5 ? :)

**Comment by iammini5** [comment]
my mistake, i was given the wrong path for test class
