### ISSUE TITLE
[Android] GIF contains cut off screenshots

### ISSUE THREAD

**Issue by mikepenz** [MarathonLabs/marathon#303]
In case a UI test on Android contains screen orientation changes, the retrieved screenshots will be rotated. This results in them being cut off in the GIF which makes it hard to actually use the GIF to check the proper execution. 

In addition the target GIF will have a small resolution if the UI was in portrait. 

It would be good if the first frame retrieved defines the orientation for the GIF, and all follow up frames are correctly adjusted according to this.

**Comment by Vacxe** [comment]
See: #304

**Comment by mikepenz** [comment]
The PR was merged. :)
