### ISSUE TITLE
Runner hangs forever on ignored android tests

### ISSUE THREAD

**Issue by BorisOsipov** [MarathonLabs/marathon#305]
I build 0.5.2 from master (https://github.com/Malinskiy/marathon/commit/11fe5894334a46e8af439d36e2eb5f0a933c6ba6)
https://gist.github.com/BorisOsipov/faadfc0e36149479ba0601a27caa38d5

When I ran tests e.g. for android sample app runner hangs forever.
I've added additional logs to identify test causes hanging and it is `ClassIgnoredTest.testAlwaysIgnored`.

See logs https://gist.github.com/BorisOsipov/faadfc0e36149479ba0601a27caa38d5

**Comment by BorisOsipov** [comment]
By git bisect I find culprit https://github.com/Malinskiy/marathon/commit/00473574ee161fee65e66c0d9bc9f578bfe73ac8

but don't know how to fix it.

**Comment by mikepenz** [comment]
Sounds like this possibly resolved the issue: https://github.com/Malinskiy/marathon/pull/314 ?

**Comment by Malinskiy** [comment]
@BorisOsipov please double check on the latest master with changes from #314

**Comment by BorisOsipov** [comment]
yes now it works well. thanks
