### ISSUE TITLE
Junit reports are generated per test case

### ISSUE THREAD

**Issue by rupinr** [MarathonLabs/marathon#313]
It is really cumbersome to work with the Junit reports generated by marathon, since they are generated per test case.
Is there are a way to combine all of them and generate one report with all of them.

**Comment by rupinr** [comment]
Improves the behaviour in https://github.com/Malinskiy/marathon/pull/319

**Comment by Malinskiy** [comment]
Closing this since we now generate one XML for the whole suite. Feel free to reopen if needed
