### ISSUE TITLE
[Discussion] Retries artifacts get lost

### ISSUE THREAD

**Issue by BorisOsipov** [MarathonLabs/marathon#322]
I use marathon for android tests. It is great tool ❤️

I noticed that screenshots(gifs) and adb logs are missing for test retries - only last execution artifacts are saved because artifacts are saved with testcase name as filename.

It isn't a big issue when test finally passed and strict mode disabled. But it will be useful to save such artifacts to investigate flaky tests reasons.
Also good test reports engines like allure can show retries in report with these artifacts and now it is broken cuz links to logs\etc lead to the same files.
Or maybe my observations are wrong?

What do you think?

**Comment by BorisOsipov** [comment]
>But it will be useful to save such artifacts to investigate flaky tests reasons.


It is a crucial feature for such a case. In docs

> Count sharding
> Executes each test count times inside each pool. For example you want to test the flakiness of a specific test hence you need to execute this test a lot of times. Instead of running the build X times just use this sharding strategy and the test will be executed X times.

 I don't have chance to investigate failures without test artifacts

**Comment by BorisOsipov** [comment]
@Vacxe @Malinskiy any thoughts about this?

**Comment by aartikov** [comment]
@Malinskiy any news about this issue?

**Comment by nimeacuerdo** [comment]
Bump

**Comment by Malinskiy** [comment]
With the latest changes in allure branch scheduled to be merged in 0.6.0 this will be supported by on-device allure reporting

Would this address the use case? Or do you want the marathon's allure report to also contain this?

**Comment by nimeacuerdo** [comment]
+1 to the latter and include them in the marathon's allure report

**Comment by Malinskiy** [comment]
Closing this: retry artifacts are now added to the reports in 0.6.2 via #499
Incomplete batches _might_ have a recording as well via b533ade8f22d37ed559dc49d5bb9cfc04a14e0a5 but this depends on the type of recording as well as the target device being healthy.

Feel free to reopen if you have any problems
