### ISSUE TITLE
Build does not fail though count sharding and Strict mode is true

### ISSUE THREAD

**Issue by kristfoograb** [MarathonLabs/marathon#331]
### Problem:
When using Count sharding and Strict mode true to run test for x number of times, Marathon does not throw SystemExitException though the test fail at least once.

The problem arise because PoolProgressTracker does not allow transition to Fail state if the test has passed previously. I believe the code was designed in this manner because test run should end with final state as pass. This is true prior to the introduction of StrictMode configuration https://github.com/Malinskiy/marathon/pull/236.

PS: This seems to be a similar issue raised in https://github.com/Malinskiy/marathon/issues/196 but the enhancement was only introduced to TestResultReporter.

### Proposed Change:
I believe changes need to be implemented in PoolProgressTracker.

```kotlin
        state<ProgressTestState.Passed> {
            on<ProgressEvent.Failed> {
                if (configuration.strictMode) {
                    transitionTo(ProgressTestState.Failed)
                }else{
                    dontTransition()
                }
            }
            on<ProgressEvent.Ignored> {
                dontTransition()
            }
        }
        state<ProgressTestState.Failed> {
            on<ProgressEvent.Passed> {
                if (configuration.strictMode) {
                    dontTransition()
                }else {
                    transitionTo(ProgressTestState.Passed)
                }
            }

        }
```

**Comment by Malinskiy** [comment]
Have you been able to confirm that the merged PR version is working for your use-case @kristfoograb?

If yes, please close the issue. Thanks 👍

**Comment by kristfoograb** [comment]
Thanks for merging.
