### ISSUE TITLE
"A Koin Application has already been started"

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#333]
Using 0.5.0's gradle plugin, I get this error running the marathon task. I assume I have everything set up correctly since the two marathon tasks show in gradle. I get the error both in the IDE and command line.

Downgrading to 0.4.1 for now.

**Comment by Malinskiy** [comment]
Hey @smugleafdev

I double checked the 0.5.0 gradle plugin at it worked perfectly fine for our sample application. This makes me believe that you might be using another gradle plugin with Koin dependency. This is a limitation of gradle plugins and is quite hard to get around (we inherit the classpath and runtime from gradle).
I suggest you try one of the following approaches:
1. Use CLI if possible. This will make sure you have a separate JVM without anything coming from gradle. FYI this is not `./gradlew marathonXXX`, you need to use the CLI application that we release (download it via releases or using homebrew)
2. Try removing other dependencies that you have in your gradle setup. By eliminating them you might find the other Koin instance. This will not solve the problem though but will provide the insight into the conflict that you have.

**Comment by folkyatina** [comment]
Hi,
I've repeated this issue with 0.5.1. Looks like marathon gradle plugin doesn't clean Koin instance on fail and it goes with such an exception when you try to relaunch it second time. 

If you kill the Gradle daemon, problem vanishes and reappear again on second try.

**Comment by tagantroy** [comment]
Fixed in #351
