### ISSUE TITLE
Gradle Plugin missing documentation for configuration

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#334]
Currently using the marathon-gradle-plugin v0.4.1 (see [issue 333](https://github.com/Malinskiy/marathon/issues/333) on why I'm not using 0.5.0). There's no documentation on configuration or even if the "Marathonfile" is usable for gradle. I came from [gojuno's composer](https://github.com/gojuno/composer) which had a well documented gradle plugin with many options for configuration, and it doesn't look like marathon has that. And if it does have the ability to reference the Marathonfile, I haven't had any luck in getting that to trigger.

**Comment by Malinskiy** [comment]
Hey @smugleafdev

Thanks for your feedback. I'd like to suggest to browse some links first:
- [official docs](https://malinskiy.github.io/marathon/doc/configuration.html#gradle)
- [common options](https://malinskiy.github.io/marathon/doc/options.html)
- [android specific options](https://malinskiy.github.io/marathon/ven/android.html)
- [samples](https://github.com/Malinskiy/marathon/blob/develop/sample/android-app/app/build.gradle.kts#L31)
- [source code](https://github.com/Malinskiy/marathon/blob/develop/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/MarathonExtension.kt#L9)

With regards to your question about Marathonfile - no, it can not be used by gradle plugin. Our suggestion is to not use the gradle plugin system at all and instead leverage the CLI application. The current gradle plugin exists for simple use-case scenarios only.

**Comment by smugleafdev** [comment]
> With regards to your question about Marathonfile - no, it can not be used by gradle plugin.

So there's no way at all to configure the gradle one? Example of composer's gradle config:

```
composer {
    withOrchestrator false
    shard true
    verboseOutput true
    apkInstallTimeout 90
    if (project.hasProperty("composerSizeTarget")) {
        instrumentationArgument('size', project.getProperty("composerSizeTarget"))
    }
}
```

**Comment by Malinskiy** [comment]
@smugleafdev As mentioned in the [docs](https://malinskiy.github.io/marathon/doc/configuration.html#gradle) you can configure the marathon-gradle-plugin via the marathon gradle extension using a _marathon {}_ block. I've posted a link to the source and samples in the message above if you want to look through the code.

In any case, you can configure almost all available options with both Marathonfile and gradle plugin configuration block. Your IDE should help you with all the available options in the _marathon {}_ block in _build.gradle(.kts)_ file.

In case you don't have experience using gradle plugins - feel free to look through the [official docs for gradle](https://docs.gradle.org/current/userguide/plugins.html)

**Comment by ZakTaccardi** [comment]
@smugleafdev you can certainly configure the gradle plugin

see:

```kotlin
// https://malinskiy.github.io/marathon/doc/options.html
// https://malinskiy.github.io/marathon/doc/configuration.html#gradle
marathon {
    name = localModule.gradlePath
    shardingStrategy {
        countSharding {
            marathonShardCountOrNull?.let {
                count = it
            }
        }
    }
    filteringConfiguration {
        whitelist {
            marathonClassOrNull?.let {
                add(
                    SimpleClassnameFilter(it.toRegex())
                )
            }
            marathonMethodOrNull?.let {
                add(
                    TestMethodFilter(it.toRegex())
                )
            }
        }
    }
}

val Project.marathonShardCountOrNull: Int?
    get() = properties["marathonShardCount"]?.let {
        Integer.valueOf(it as String)
    }
val Project.marathonMethodOrNull: String?
    get() = properties["marathonMethod"]?.let {
        it as String
    }
val Project.marathonClassOrNull: String?
    get() = properties["marathonClass"]?.let {
        it as String
    }
```

this is something like the suggestion here:

https://github.com/jaredsburrows/gradle-spoon-plugin/issues/35

this allows creation of an API like:

```
./gradlew :lib:marathonDebugAndroidTest -PmarathonClass=FragmentTest -PmarathonMethod=noTimeout -PmarathonShardCount=30
```

**Comment by Malinskiy** [comment]
All the docs have been updated awhile ago with samples for configuration for both gradle and Marathonfile.
I'm going to close this. Feel free to reopen.
