### ISSUE TITLE
Screen Videos are Zero Size

### ISSUE THREAD

**Issue by ghost** [MarathonLabs/marathon#336]
Screen videos for failed tests are being created, but their size is 0.

Using Marathon Gradle Plugin 0.5.0-Snapshot

Not sure how to debug this.

**Comment by smugleafdev** [comment]
Have you tried different devices or APIs? Would be helpful to know if it's for specific versions of Android or all.

**Comment by Malinskiy** [comment]
Hey @shoeguy

Can you provide more info on the devices that you're using for the tests?
Some android emulator versions report as video capture as supported, but in reality they produce empty files. You can verify if the device actually produces a video file with the [screenrecord](https://developer.android.com/studio/command-line/adb#screenrecord) utility.

Another case when this can happen is unstable adb connection.

Please post the results of your findings with `screenrecord` and we will help you debug this issue further.

Thanks

**Comment by BorisOsipov** [comment]
Hi, Anton!

I ran into the same issue. 
I've checked in my docker android emulator `screenrecord` cannot record video due high resolution
```
generic_x86:/ $ screenrecord --verbose /sdcard/demo.mp4
Main display is 1440x3040 @60.00fps (orientation=0)
Configuring recorder for 1440x3040 video/avc at 20.00Mbps
Content area is 1440x3040 at offset x=0 y=0
Unable to get output buffers (err=-38)
Encoder failed (err=-38)
Stopping encoder and muxer
```
If I change resolution to lower value e.g.  `1280x720` `screenrecord` works just fine. Output
```
generic_x86:/ $ screenrecord --verbose /sdcard/demo.mp4 --size 1280x720
Main display is 1440x3040 @60.00fps (orientation=0)
Configuring recorder for 1280x720 video/avc at 20.00Mbps
Content area is 341x720 at offset x=469 y=0
^CEncoder stopping; recorded 8 frames in 76 seconds
```

Maybe you could give some piece of advice how can I fix video recording in `marathon` or tune emulator?

Now I use https://github.com/budtmo/docker-android emulators with skin https://github.com/budtmo/docker-android/blob/f5e273d05c275eba9f4a2347d2ad621ee6f28063/devices/profiles/samsung_galaxy_s10.xml

Thanks in advance.

**Comment by BorisOsipov** [comment]
I see recording options are constants. See https://github.com/Malinskiy/marathon/blob/cc3985fe0abd1ad071766108ff3517de487e9fe1/vendor/vendor-android/base/src/main/kotlin/com/malinskiy/marathon/android/executor/listeners/video/ScreenRecorder.kt#L34-L46

What do you think about moving it into `vendorConfiguration` and allow to change?

**Comment by Malinskiy** [comment]
@BorisOsipov sounds like a good solution to the problem :+1:. I'm a bit worried that the configuration is not discoverable at the moment so we don't have a way of reducing the size in case we find error on the device. But as a first step we can make this option configurable. Later maybe we can reduce the size dynamically if the recording keeps failing.
Anyone up to make the necessary changes to pull these constants up to the android configuration?

**Comment by ghost** [comment]
I've only ever been able to do screen recording on an emulator using a specific size:

```
                    if (device.isEmulator()) {
                        argument_size = "--size 1280x720";
                    }
```

**Comment by Malinskiy** [comment]
Screen recording configuration has been reworked awhile ago, see the docs here https://malinskiy.github.io/marathon/ven/android.html#screen-recorder-configuration

All of these options are now configurable and can be overridden in case of problems like this. I'll close the issue for now, feel free to reopen if there is something else that needs work here.
