### ISSUE TITLE
Log File page just shows processing.

### ISSUE THREAD

**Issue by ghost** [MarathonLabs/marathon#337]
When clicking through to a log file, the page just shows the processing dots but never displays the log.  I did check the directory and the log file does exist.

![image](https://user-images.githubusercontent.com/31056004/75718639-ec738700-5c98-11ea-84f1-83ffaf6220c3.png)

**Comment by ghost** [comment]
There is really nothing to review since one file updated has too many diffs to be shown.  Is there a way for me to download the file and test it?

**Comment by Malinskiy** [comment]
@shoeguy I'd suggest to `git checkout fix/reporting_logs_infinite_loading`. Alternatively, here is a [link to the actual file](https://raw.githubusercontent.com/Malinskiy/marathon/3cb6bb225f9333a25ae39e8f8e14500379d62180/report/html-report/src/main/resources/html-report/app.min.js)
