### ISSUE TITLE
Misleading documentation for setup

### ISSUE THREAD

**Issue by folkyatina** [MarathonLabs/marathon#339]
[Downloading](https://malinskiy.github.io/marathon/doc/downloading.html) section says that all you should do is to add 

`id 'marathon' version 'X.X.X'`

to your build.gradle to add the plugin, but it will not work without this little magic in settings.gradle: 

```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "marathon") {
                useModule("com.malinskiy.marathon:marathon-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

I think adding this to the doc will streamline setup process a lot.

**Comment by Malinskiy** [comment]
Added this to the docs https://malinskiy.github.io/marathon/doc/downloading.html. Thank you!
