### ISSUE TITLE
Successful test run but logs are MIA

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#355]
```
testRunStarted EMULATOR30X0X5X0
testStarted EMULATOR30X0X5X0 test = TestIdentifier(className=component_ui_tests.ChallengeSelectionUiTest, testName=noMethodsAvailableTest)
88% | [omni]-[EMULATOR30X0X5X0] component_ui_tests.ChallengeSelectionUiTest#noMethodsAvailableTest started
join 1003ms
Removed file in 786ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-noMethodsAvailableTest.mp4
testEnded EMULATOR30X0X5X0 test = TestIdentifier(className=component_ui_tests.ChallengeSelectionUiTest, testName=noMethodsAvailableTest)
100% | [omni]-[EMULATOR30X0X5X0] component_ui_tests.ChallengeSelectionUiTest#noMethodsAvailableTest ended
testRunEnded elapsedTime 3679

> Task :challenge:challenge-implementation:marathonDebugAndroidTest
handle test results EMULATOR30X0X5X0
request next batch for device EMULATOR30X0X5X0
terminate EMULATOR30X0X5X0

Recording finished in 4984ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-noMethodsAvailableTest.mp4
Recording finished in 24284ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-phoneStableUnstable_1.mp4
Recording finished in 31160ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-phoneStableUnstable_2.mp4
Recording finished in 40965ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-phoneStableUnstable_4.mp4
Recording finished in 17526ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-otpEmailInAndOut.mp4
Recording finished in 45761ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-phoneStableUnstable_5.mp4
Recording finished in 36341ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-phoneStableUnstable_3.mp4
Recording finished in 55646ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-enterChallengeMethodsAndCancelTest.mp4

> Task :challenge:challenge-implementation:marathonDebugAndroidTest
Allure environment data saved.
Marathon run finished:
Device pool omni:
        8 passed, 0 failed, 0 ignored tests
        Flakiness overhead: 0ms
        Raw: 8 passed, 0 failed, 0 ignored, 0 incomplete tests
Total time: 0H 1m 0s


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 9s
832 actionable tasks: 1 executed, 831 up-to-date
```

However, logs for the test never load.

<img width="975" alt="Screen Shot 2020-04-24 at 3 27 15 PM" src="https://user-images.githubusercontent.com/461114/80250462-edde8180-8641-11ea-9b57-294e01db833e.png">

**Comment by Malinskiy** [comment]
Are the logs present in the directory output `reports/marathon/logs`?

**Comment by ZakTaccardi** [comment]
yep! I ran 8 tests, seeing 8 log files under `reports/marathon/debugAndroidTest/logs/omni/emulator-5554/`

Looking at the `reports/marathon/debugAndroidTest/video/omni/emulator-5554/` folder, I only see 1 `.mp4` (when there should be 8), which seems to be corrupted as it can't be played and it's of `0s` length

**Comment by ZakTaccardi** [comment]
oh - forgot to mention that I'm seeing an issue too where the `.mp4` recordings aren't accessible from the HTML report

**Comment by Malinskiy** [comment]
Which version of marathon are you using? Do the log files have content?

With the video - this is a known issue with some devices: the `screenrecorder` binary might not work properly on them. You can double check if it works by running `adb shell screenrecorder`. Marathon detects only the presence of this binary and assumes that it's working.

**Comment by ZakTaccardi** [comment]
> Which version of marathon are you using?

`0.5.2`

> Do the log files have content?

Yes

> `adb shell screenrecorder`

output is:

```
adb shell screenrecorder
/system/bin/sh: screenrecorder: inaccessible or not found
```

**Comment by ZakTaccardi** [comment]
> Marathon detects only the presence of this binary and assumes that it's working.

Is there a way to disable screen recording?

btw, with the same emulator above, I see:

```
> Task :challenge:challenge-implementation:marathonDebugAndroidTest
handle test results EMULATOR30X0X5X0
request next batch for device EMULATOR30X0X5X0
terminate EMULATOR30X0X5X0

Recording finished in 2970ms /sdcard/component_ui_tests.ChallengeSelectionUiTest-noMethodsAvailableTest.mp4

> Task :challenge:challenge-implementation:marathonDebugAndroidTest
Allure environment data saved.
Marathon run finished:
Device pool omni:
        1 passed, 0 failed, 0 ignored tests
        Flakiness overhead: 0ms
        Raw: 1 passed, 0 failed, 0 ignored, 0 incomplete tests
Total time: 0H 0m 9s


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 23s
832 actionable tasks: 410 executed, 421 from cache, 1 up-to-date
```

Though this recording may end up being deleted automatically because the test succeeded?

**Comment by Malinskiy** [comment]
You can force the recoding type with the [preferableRecorderType](https://github.com/Malinskiy/marathon/blob/develop/cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileAndroidConfiguration.kt#L24) option

**Comment by ZakTaccardi** [comment]
looks like `preferableRecorderType` is missing from the [documentation](https://malinskiy.github.io/marathon/doc/options.html)

also, the below flag is not mutable

```
val screenRecordingPolicy: ScreenRecordingPolicy? = null
```

so:

```
// val cannot be reassigned
screenRecordingPolicy = ScreenRecordingPolicy.ON_ANY
```

**Comment by ZakTaccardi** [comment]
btw, I checked out the console logs in Chrome, and the exception I am seeing is when loading the logs is:

```
Access to XMLHttpRequest at 'file:///Users/zak/Development/git/my-sdk/lib/build/reports/marathon/debugAndroidTest/logs/omni/EMULATOR30X0X5X0/component_ui_tests.MyTest%23noMethodsAvailableTest.log' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

**Comment by Malinskiy** [comment]
@ZakTaccardi You need to server the html from an actual HTTP server. IntelliJ has internal one or you can use an Nginx container

The configuration is deserialized from JSON for CLI so you should be able to specify the screenRecordingPolicy easily

**Comment by ZakTaccardi** [comment]
> You need to server the html from an actual HTTP server. IntelliJ has internal one or you can use an Nginx container

This seems to be a design flaw and a serious barrier to entry. As a developer who is looking to replace Spoon (which supports this use case) with Marathon, it would be much preferred to be able to click through the report directly

**Comment by Malinskiy** [comment]
@ZakTaccardi this is not a limitation of marathon, but a limitation of browsers that care about your security and block suspicious cross-site requests .

For a CI use-case, there is no such issue since all of them share the report via some form of HTTP server.
For a local development use-case: most people use an IDE and have the HTTP server there. Just right click on the report HTML and open in your browser of choice. If you're a vim/emacs adept then you should be able to start a `docker run` with nginx without any issue.

The only way to overcome this in marathon is to embed the content directly into the HTML which I don't think should be done: this will increase the size almost twice for the report directory. These video/screenshot/log files are shared between multiple reports that we generate and duplicating them would not be feasible.

**Comment by ZakTaccardi** [comment]
I was able to start a web server by navigating to the `build/reports/marathon/debugAndroidTest` directory and running:

```
python3 -m http.server 8000
```

then going to `http://localhost:8000`

**Comment by ZakTaccardi** [comment]
Should I be starting the server at:

```
build/reports/marathon/debugAndroidTest/
```

or
```
build/reports/marathon/debugAndroidTest/html
```

I tried both, with the following two commands on a Mac

```
sudo apachectl start
```

```
python3 -m http.server --cgi 8080
```

but neither worked.

**Comment by trevjonez** [comment]
python cli server is a great workaround that is still valid today. Much easier than opening a downloaded CI report ZIP inside of studio/idea.
