### ISSUE TITLE
How to run the test on iOS devices locally when I don't have access to admin?

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#369]
Hey Guys,

I am trying to run the tests on iOS devices locally because I do not have admin rights to my Mac. When I put in localhost in the Marathondevices file - The execution stops saying Failed to initialize the device with the udid <udid>with reason unknown
. While I put in my ip address the command looks for the tests and finds them but throws a UserAuthException exhausted available authentication methods.

I have generated the .xctestrunfile on the before-hand.

vendorConfiguration:
  type: "iOS"
  xctestrunPath: "MyApp_iphonesimulator11.0-x86_64.xctestrun"
  derivedDataDir: "a"
  remoteUsername: "sparepal"
  remotePrivateKey: "/Users/sparepal/.ssh/id_rsa"
  knownHostsPath: "known_hosts"
  remoteRsyncPath: "/usr/local/bin/rsync"
  debugSsh: true

**Comment by Malinskiy** [comment]
Hey @sparepal 

Can you please try using the https://github.com/Malinskiy/marathon/blob/develop/sample/ios-app/ios-app-setup.sh script and see if that helps you with the initial setup?

All the transport for iOS devices happens via ssh in marathon's `vendor-ios`. I'm not sure if you can start up the ssh server on your Apple device without admin permissions though, you'd have to test this out.

**Comment by sparepal** [comment]
Hello Guys,

Following up on this. Without admin rights I am able to create a fake ssh server and send commands to the server via client as an example on 127.0.01. But when I run the same from marathon as the client I get host key not verified. 

Is there a way to fix this on marathon side?

**Comment by sparepal** [comment]
Another question.
According to my compliance I am not allowed to use ssh.
Is it possible to run the iOS tasks with bypassing the ssh only on the local devices?

**Comment by Malinskiy** [comment]
@sparepal at the moment it's not possible to use vendor-ios without ssh. In theory, it's possible to write an implementation that only uses local shell executor but there is not much interest in using such vendor so far: marathon is geared towards running thousands of tests and hence requires dozens of devices which is not possible on just one machine.

@tagantroy was experimenting with using https://github.com/facebook/idb, if you want to get involved in creating a new iOS vendor - please get in touch with him

**Comment by Malinskiy** [comment]
Regarding the issue with host key verification: #265
If you want to force disable the verification there is a flag `disableHostKeyVerifier`

I'd strongly suggest investigating why your setup doesn't work. There are samples on doing a local setup with key verification in https://github.com/Malinskiy/marathon/blob/develop/sample/ios-app/ios-app-setup.sh, please compare then to your local setup.

**Comment by sparepal** [comment]
Regarding the disableHostKeyVerifier. When do I need to place the flag?

**Comment by sparepal** [comment]
Okay now I have admin access.
Currently I am trying to run the sample/ios-app.
All my test cases are failing and not completion,is that how that's supposed to happen?

**Comment by sparepal** [comment]
Was a mistake at my end, works now.
