### ISSUE TITLE
missing dependencies in configuration

### ISSUE THREAD

**Issue by zoey-juan** [MarathonLabs/marathon#37]
missing dependencies when apply plugin: 'marathon'
`Caused by: java.lang.NoClassDefFoundError: com/malinskiy/marathon/execution/Configuration`
unless add dependencies by adding "com.malinskiy.marathon:core"

**Comment by Malinskiy** [comment]
Sounds like we don't propagate the dependecies in POM

**Comment by dsvoronin** [comment]
i can't reproduce it in 0.1.3

**Comment by Malinskiy** [comment]
unable to reproduce. please reopen the issue again if the problem appears again
