### ISSUE TITLE
Remote Android tests

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#370]
Is it possible to run Android tests on another system by using the ipAddress assuming marathon is setup on the remote system, we have the path to the apk's and valid config respective to the remote system?

**Comment by Malinskiy** [comment]
Hey @sparepal

I don't really understand your setup from the question. Let me clarify though that marathon needs a local adb server to have android devices connected. These can be local emulators or remote emulators or remote/actual phones.

If your remote device is properly set up you can connect it to the local instance of adb server as following:
```
adb connect device_ip_address:device_adb_port
```

Marathon will then execute tests in parallel using as many remote devices as you connect.

If you happen to run OpenSTF for your device farm then you can request these devices using [stf-client](https://github.com/Malinskiy/stf-client)

Does this answer your question?

**Comment by sparepal** [comment]
Let me try this and get back to you. I will close the issue if this works and meets my need. 
Thanks Malinksiy!

**Comment by sparepal** [comment]
Works with adb connect. 
Thanks Malinskiy!
