### ISSUE TITLE
Pushing results to SQL database 

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#376]
I am able to run the test and see that the results are pushed to the influxDB. Is there any way I could redirect the results to store in SQL database even if I have to modify the source code? 
Or is it gonna take me too much refactoring?

**Comment by Malinskiy** [comment]
Hey @sparepal 
You'd have to implement the data store for the remote metrics

The datasource abstraction is [here](https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/analytics/metrics/remote/RemoteDataSource.kt#L15)

There is currently only one implementation for it being [influxdb](https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/analytics/metrics/remote/influx/InfluxDBDataSource.kt) but it shouldn't be too hard to implement the logic with MySQL. Although you should keep in mind that the requests should complete in reasonable amount of time: some of them request over a month of historical data and even InfluxDB can take up to 30 seconds to fetch the result. This should definitely be tested in the implementation. Please reach out to us if you will proceed with the actual implementation! :)

**Comment by sparepal** [comment]
Hey I was able to push the results to the sql DB. Thanks for you support!
