### ISSUE TITLE
Windows os support

### ISSUE THREAD

**Issue by sergiilisovskyi** [MarathonLabs/marathon#379]
Hi, 

Is it possible to run marathon on windows OS ?

Thanks

**Comment by Malinskiy** [comment]
Hey @sergiilisovskyi 
It should be possible to run marathon on windows since everything is JVM based. I haven't tested it though especially for ios vendor. What kind of project are you trying to test? Have you tried using the CLI?

**Comment by sergiilisovskyi** [comment]
Hi Anton, 

Actually I'm trying to test android app based on espresso framework.
In future iOS testing based on XCUITest framework is considered too.

Looks like everything works as expected.

P.S. I would like to say a big thank you. 
Really appreciate such a great contribution.

**Comment by Malinskiy** [comment]
I double-checked on a Windows machine: the example project works as expected. If you see any issues - please reopen
