### ISSUE TITLE
ScreenRecordConfiguration option is not available

### ISSUE THREAD

**Issue by sergiilisovskyi** [MarathonLabs/marathon#380]
Hi guys,

When I'm trying to add  a screenRecordConfiguration option, marathon failed due to
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "screenRecordConfiguration"

Config file:
.....
vendorConfiguration:
  type: "Android"
  applicationApk: "path_to_apk"
  testApplicationApk: "path_to_apk"
  serialStrategy: "DDMS"
  preferableRecorderType: "video"
  screenRecordConfiguration: 
   videoConfiguration:
    enabled: true
    width: 720
    height: 1280
    bitrateMbps: 1
    timeLimit: 180 //seconds
   screenshotConfiguration:
    enabled: true
    width: 720
    height: 1280
    delayMs: 500

**Comment by Malinskiy** [comment]
The `screenRecordConfiguration` was introduced recently and is not available in released versions, only in snapshot.

For the future, please fill out the expected info from the issue template: marathon version and etc

**Comment by sergiilisovskyi** [comment]
Sure.

Thanks.
