### ISSUE TITLE
The log file is displayed in Edge browser only. 

### ISSUE THREAD

**Issue by sergiilisovskyi** [MarathonLabs/marathon#381]
Hi guys,

Please try to open Log file in generated html file in different browsers.
I tried to do that on Windows (Chrome, Edge, Firefox) and on Mac (Safari).

The log was successfully displayed only in Windows Edge browser, in other cases it hangs in processing state. 
![dots](https://user-images.githubusercontent.com/20441322/84595231-5cc8a180-ae5f-11ea-990b-0f0e7e3dfb64.png)

**Comment by Malinskiy** [comment]
Have you started a web-server for serving these HTML report? Probably related to #355

Otherwise you would see XSS security warning and the browser will prevent you from using the `file:` links

**Comment by sergiilisovskyi** [comment]
Hi Anton,

Seems like it duplicates https://github.com/Malinskiy/marathon/issues/355

Thanks.
