### ISSUE TITLE
Coroutines build error with 0.6.0-SNAPSHOT version

### ISSUE THREAD

**Issue by QAutomatron** [MarathonLabs/marathon#386]
**Describe the bug**
When building a project using `marathon-gradle-plugin` version `0.6.0-SNAPSHOT` there is coroutine error.

**To Reproduce**
Start test run using `./gradlew :app:marathonDebugAndroidTest`

Plugin set-up:
```
 plugins { id 'marathon' version '0.6.0-SNAPSHOT' }

pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "marathon") {
                useModule("com.malinskiy.marathon:marathon-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

**Expected behavior**
Build should be ok. 

**Logs and reports**
```
14:16:50  kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=BlockingCoroutine{Cancelling}@150fc1b9
14:16:50  Device Unknown booted!
14:16:50  Device 172.17.0.1:5623 connected. Healthy = true
14:16:50  Device Unknown booted!
14:16:50  
14:16:50  FAILURE: Build failed with an exception.
14:16:50  
14:16:50  * What went wrong:
14:16:50  Execution failed for task ':app:marathonDebugAndroidTest'.
14:16:50  > kotlinx.coroutines.channels.ChannelIterator.next()Ljava/lang/Object;
```

**Devices (please complete the following information):**
 - Device: Emulator
 - OS: Android (API 28)

**Additional context**
Do I need to add coroutines to classpath manually as it's used in `sample` project?

**Comment by Malinskiy** [comment]
@QAutomatron yes, you need to manually add coroutines dependency to your classpath. This is one of the reasons why it's suggested in the docs to use CLI: we can fully predict the classpath. In the case of gradle, we observed several libraries that behave in a strange way like this [coroutines problem](https://github.com/Malinskiy/marathon/blob/develop/sample/android-app/build.gradle.kts#L10)

**Comment by QAutomatron** [comment]
Got it, thanks, will try switching to CLI

**Comment by Malinskiy** [comment]
Closing. Feel free to reopen if there is additional info about the issue.
