### ISSUE TITLE
Provide option to set up path for Marathonfile.

### ISSUE THREAD

**Issue by sergiilisovskyi** [MarathonLabs/marathon#391]
**Describe the bug**
Provide option to set up path for Marathonfile

**To Reproduce**
Steps to reproduce the behaviour:
1. Change default location of Marathonfile (e.g. from marathon\bin\Marathonfile  to marathon\bin\testApkFolder\Marathonfile)
2. Run marathon executable

**Actual behavior**
Error: Could not find or load main class patient\com.malinskiy.marathon.cli.ApplicationViewKt

**Expected behavior**
Marathon test run starts as expected

**Actual for all platforms**

**Comment by tagantroy** [comment]
Hello @sergiilisovskyi 
It is already available, 
for example `marathon -m testApkFolder\Marathonfile`

**Comment by sergiilisovskyi** [comment]
Thanks
