### ISSUE TITLE
Graphite support

### ISSUE THREAD

**Issue by bartek-wesolowski** [MarathonLabs/marathon#400]
Marathon supports gathering test statistics using InfluxDB. You can then visualize them with Graphite.
It would be great to be able to use Graphite instead of InfluxDB as the underlying database. In our company we use Graphite for other statistics and we could integrate it with Marathon easily without the need of having to host another tool.

**Comment by bartek-wesolowski** [comment]
I'm working on it. It should be done in a couple of days.

**Comment by bartek-wesolowski** [comment]
I added Graphite support, but I don't seem to have the necessary repository permissions to push the changes. Here's the patch file. Please, give me the necessary permissions or apply it yourself.

[graphite.patch.zip](https://github.com/Malinskiy/marathon/files/5347515/graphite.patch.zip)

**Comment by tagantroy** [comment]
Thanks for your contribution. 
#406 and #408 merged 
Please reopen if there anything else to do.
