### ISSUE TITLE
InfluxDB 2.x support

### ISSUE THREAD

**Issue by bartek-wesolowski** [MarathonLabs/marathon#401]
Currently, Marathon uses [influxdb-java](https://github.com/influxdata/influxdb-java) to connect to InfluxDB. The library only supports InfluxDB 1.x while there's already InfluxDB 2.x which is not supported. [influxdb-client-java](https://github.com/influxdata/influxdb-client-java) should be used instead of [influxdb-java](https://github.com/influxdata/influxdb-java) to provide InfluxDB 2.x support (see the current library's [README](https://github.com/influxdata/influxdb-java/blob/master/README.md)).

**Comment by tagantroy** [comment]
Hello @bartek-wesolowski, 
I think we should consider refactoring of analytics to make it pluggable and support more data sources.
As you mentioned in #400 Graphite support would be good to have in the Marathon.
Other issues about analytics: #104 #201 #365 #400 #401 

We have abstraction for Remote data sources https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/analytics/metrics/remote/RemoteDataSource.kt (Influx db implementation https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/analytics/metrics/remote/influx/InfluxDBDataSource.kt) 
I think it should be easy to implement support for Graphine and new version of InfluxDB using RemoteDataSource.

I would be happy to review your pull requests :) 
I'll try work on this on weekend.
If you have any ideas for other data storages, please share it here

**Comment by trevjonez** [comment]
100% agree with @tagantroy about making it more easily pluggable. I'd be happy to contribtue an AWS timestream impl of such an interface.

https://aws.amazon.com/timestream/

Then adding a bit of terraform/cloudformation for existing virtual device farms that run on marathon would be quite trivial in comparison to standing up an instance influx.

**Comment by Malinskiy** [comment]
@trevjonez fyi: example of plugging in for analytics backend would be https://github.com/Malinskiy/marathon/pull/406

**Comment by trevjonez** [comment]
Ahh perfect, last I looked it was not quite interfaced out enough to keep it simple.

**Comment by trevjonez** [comment]
Ended up deciding to just standup influx on my cluster so I may take a swing at adding v2 support rather than timestream.
