### ISSUE TITLE
Please rename blacklist configuration to blocklist

### ISSUE THREAD

**Issue by hborders** [MarathonLabs/marathon#402]
**Describe the bug**
(I don't know the background of the developers of this project, and I don't presume that developers have malicious intent or are trying to exclude people from using or contributing to this project.) In the US, `blacklist` is a racist term. `blocklist` is a term free of racial meaning. Please rename the `blacklist` configuration to `blocklist`.

Thank you for this terrific project!

**Comment by Malinskiy** [comment]
Hey @hborders. 

Thanks for reporting this. I think it would be unfair to rename only blacklist to blocklist. Whitelist should also be renamed appropriately.

If you have time to spend on this issue - I'd be happy to accept a Pull Request from you that doesn't break our current userbase (i.e. doesn't break their `Marathonfile` and gradle setups).

**Comment by hborders** [comment]
Do you have a preferred `whitelist` replacement term?

I was thinking `acceptlist`.

**Comment by Malinskiy** [comment]
I think we could reuse the [chromium project's](https://chromium-review.googlesource.com/c/chromium/src/+/2234793) terminology.

- Replaced blacklist references with blocklist
- Replaced whitelist references with allowlist

What do you think?

**Comment by tagantroy** [comment]
@Malinskiy +1 for allowlist + blocklist

**Comment by hborders** [comment]
Thanks for being so responsive to this!

👍🏻 `allowlist` and `blocklist`
