### ISSUE TITLE
Disable video recording

### ISSUE THREAD

**Issue by ivincetti** [MarathonLabs/marathon#414]
In our app we work with video, and new video at root of storage is breaking tests.

In sample
https://github.com/Malinskiy/marathon/blob/2689d7b2a563db09e88e6753912eeed9bf4bd929/cli/src/test/resources/fixture/config/sample_1.yaml

there is:
screenRecordConfiguration
  videoConfiguration:
      enabled: false
 screenshotConfiguration:
      enabled: false

but with this options on marathon start, I get a error:
```
Exception in thread "main" com.malinskiy.marathon.exceptions.ConfigurationException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "screenRecordConfiguration" (class com.malinskiy.marathon.cli.args.FileAndroidConfiguration), not marked as ignorable (12 known properties: "applicationPmClear", "testApplicationPmClear", "installOptions", "serialStrategy", "vendor", "androidSdk", "applicationApk", "testApplicationApk", "preferableRecorderType", "adbInitTimeoutMillis", "instrumentationArgs", "autoGrantPermission"])
19:21:32     at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.malinskiy.marathon.cli.args.FileConfiguration["vendorConfiguration"]-
```

1. Full configuration Marathonfile.  Version of marathon 0.5.2
```
name: "UI Tests"
outputDir: "./build/marathon"
poolingStrategy:
  - type: "omni"
  - type: "device-model"
  - type: "os-version"
  - type: "manufacturer"
  - type: "abi"
shardingStrategy:
  type: "count"
  count: 1
batchingStrategy:
  type: "fixed-size"
  size: 10
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 2
ignoreFailures: false
strictMode: true
debug: false
deviceInitializationTimeoutMillis: 300000
vendorConfiguration:
  type: "Android"
  applicationApk: "app/build/outputs/apk/staging/debugstaging-debug.apk"
  testApplicationApk: "app/build/outputs/apk/androidTest/staging/debug/staging-debug-androidTest.apk"
  serialStrategy: "ddms"
  screenRecordConfiguration:
    preferableRecorderType: "screenshot"
    videoConfiguration:
      enabled: false
    screenshotConfiguration:
      enabled: false
  waitForDevicesTimeoutMillis: 15000
```

**Comment by Malinskiy** [comment]
Hi @ivincetti . I'm not sure if you're familiar with yaml, the indentation is important for this particular format.
Could you please make sure you're using properly formatted configuration? You can also use the block ``` markdown syntax here in the issue to show indentation that you're using.
Thanks

**Comment by ivincetti** [comment]
Hi! Fixed question syntax. Version 0.5.2

**Comment by Malinskiy** [comment]
This configuration option is available only on shapshot at the moment since it was introduced after 0.5.2 (which is the latest stable at the moment). Can you use the snapshot for now until we release 0.6.0?

**Comment by ivincetti** [comment]
I think it's not a problem. but i cannot find information about install SNAPSHOT version. 

i need build it from repo?

**Comment by Malinskiy** [comment]
Yes, you can run `./gradlew :cli:distZip` to get the zip in the `cli/build/distributions` folder.
I'm not sure if we can upload this to OSS sonatype, I'll check if it's possible later this week so that we get a snapshot CLI build people can use.

**Comment by ivincetti** [comment]
Thank you very much!
I'l try it tomorrow morning and write back about results

**Comment by ivincetti** [comment]
all works like a charm )
