### ISSUE TITLE
Execution failed for task mobile:marathonDevDebugAndroidTest

### ISSUE THREAD

**Issue by automaticqa** [MarathonLabs/marathon#416]
Hello guys,
can you help me please with this problem:
when i start marathonDevDebugAndroidTest task, i get next error:
```
Execution failed for task ':mobile:marathonDevDebugAndroidTest'.
> org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
```
Would you give me some advice please how to figure out it?

**Comment by Malinskiy** [comment]
Related to #357. I'm not sure if this is something that is isolated in the marathon gradle plugin. Would you please check the suggestion that was given in that issue for stopping the gradle daemon?

**Comment by automaticqa** [comment]
Thank you very much
