### ISSUE TITLE
Marathon stops adb server after it terminates

### ISSUE THREAD

**Issue by mikepenz** [MarathonLabs/marathon#431]
**Describe the bug**

Using v0.6.0 of marathon it seems that the `adb` server gets terminated after each run, resulting in a new start of the server afterwards. 

It seems this results in devices to get into an `OFFLINE` state more frequent. 

PR #377 introduced ddmlib 27.0.0 https://github.com/Malinskiy/marathon/pull/377 

The latest version of ddmlib 27.1.1 (https://maven.google.com/web/index.html?q=ddmlib#com.android.tools.ddms:ddmlib:27.1.1) offers a config so the server does not get terminated. https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-mast[…]src/main/java/com/android/ddmlib/AndroidDebugBridge.java

**To Reproduce**
- run marathon
- run marathon a second time
  - results in the adb server to start again

**Expected behavior**
- adb server is not stopped after the run

**Logs and reports**

- marathon 0.6.0
- ddmlib vendor
- Host OS: Mac OS X BigSur / Ubuntu 

**Additional context**
- https://marathon-test-runner.slack.com/archives/CDYCJ2C3W/p1609922723000800

**Comment by bartek-wesolowski** [comment]
I'm having the same issue.

**Comment by mikepenz** [comment]
@bartek-wesolowski adding the env flag  `export ANDROID_ADB_USER_MANAGED_MODE=true` makes it work. so that's a good workaround

**Comment by bartek-wesolowski** [comment]
@mikepenz what is this flag? When I google it I get nothing.

**Comment by mikepenz** [comment]
https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/ddmlib/src/main/java/com/android/ddmlib/AndroidDebugBridge.java#272

**Comment by mikepenz** [comment]
It will result in adb not being stopped at the end.

**Comment by bartek-wesolowski** [comment]
Setting `ANDROID_ADB_USER_MANAGED_MODE=true` didn't work for me.

**Comment by Malinskiy** [comment]
@bartek-wesolowski the fix will be included in the next release of marathon. In the meantime you can try out the version from develop to double check if the solution works for you.

How did you set up the envvar? Just curious why this didn't work in your case

**Comment by bartek-wesolowski** [comment]
I added `ANDROID_ADB_USER_MANAGED_MODE=true` to Bamboo's environment variables field. I've done it before with other variables and they worked. Bamboo displayed this variable in build logs as well.
![Zrzut ekranu 2021-02-4 o 14 05 17](https://user-images.githubusercontent.com/3972790/106896686-34ddc500-66f2-11eb-845f-62f84d226dc0.png)
