### ISSUE TITLE
CLI stuck when NoDevicesException is thrown

### ISSUE THREAD

**Issue by pavel-vasilev** [MarathonLabs/marathon#437]
**Describe the bug**
Starting from marathon 0.5.2, marathon not stop its process after any encountered errors when run from cli

**Marathon 0.6.0**
<img width="1118" alt="Снимок экрана 2021-01-28 в 14 48 16" src="https://user-images.githubusercontent.com/46404556/106137968-8f1fd880-617c-11eb-888f-51e6a5ac2738.png">

**Marathon 0.5.1**
<img width="1129" alt="Снимок экрана 2021-01-28 в 15 21 01" src="https://user-images.githubusercontent.com/46404556/106138224-e625ad80-617c-11eb-99bd-4bc631dd6c48.png">

**Expected behavior**
Stop marathon process after any encountered error

**Comment by Malinskiy** [comment]
Please be more specific with any errors here. If it's just the no devices found - that's one thing, if it's any error - it's a completely different issue.

**Comment by pavel-vasilev** [comment]
@Malinskiy ye, you right. Cli stuck only after no device error. Parsing error correctly stop marathon process

**Comment by Malinskiy** [comment]
@pavel-vasilev I can't reproduce this after the changes in #426. Can you please try the latest version from develop?

**Comment by pavel-vasilev** [comment]
@Malinskiy tried, but got same result. To clearify my Marathonfile have this option set to true `ignoreFailures`. So the process not exited with code 1 and just stuck.
```kotlin
val shouldReportFailure = !configuration.ignoreFailures
if (!success && shouldReportFailure) {
    throw SystemExitException("Build failed", 1)
}
```
Maybe rewrite main function from 
```kotlin
main() = mainBody() { ... }
```
to
```kotlin
main() {
    mainBody() { ... }
    exitProcess(0)
}
```

**Comment by Malinskiy** [comment]
@pavel-vasilev the `ignoreFailures` flag was the important bit we were missing here.
This problem only happens for ddmlib device provider: the ddmlib seems to highjack the termination unless we terminate it explicitly. 

Please test on #445 and I'll merge it if your use-case is resolved.
Cheers
