### ISSUE TITLE
Change Android Vendor to ADAM in Gradle configuration

### ISSUE THREAD

**Issue by asos-jorgegonzalez** [MarathonLabs/marathon#440]
I want to switch to ADAM Vendor using the Gradle configurationo but I can't achieve it due to this error: 
```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'com' for extension 'marathon' of type com.malinskiy.marathon.MarathonExtension.
```
How can I import the vendor into the Marathon config? What am I missing?

My files:

**root/settings.gradle**
```
pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://dl.bintray.com/qameta/maven' }
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "marathon") {
                useModule("com.malinskiy.marathon:marathon-gradle-plugin:0.6.0")
            }
        }
    }
}

[...]
```

**root/build.gradle**
```
buildscript {
    repositories {
        [...]
    }
    dependencies {
        classpath "com.malinskiy.marathon:marathon-gradle-plugin:0.6.0"

        [...]        
    }
}

[...]
```

**root/app/build.gradle**
```
apply plugin: 'marathon'

marathon {

    vendor = com.malinskiy.marathon.android.VendorType.ADAM // <----

    [...]
}
```

**Comment by Malinskiy** [comment]
Hey @asos-jorgegonzalez 
I'll check this today or tomorrow and will get back to you

My only suspicion is that you might need an import statement since gradle interprets this as a property rather than FQDN

**Comment by asos-jorgegonzalez** [comment]
Thanks! Is it possible that the cause is that Vendor type is declared in a different module than `marathon-gradle-plugin`? Then we don't have access to it. The same issue happens if you want to use ScreenRecordConfigurations. I tried to add those maven modules into **root/build.gradle**, but it doesn't work.
```
buildscript {
    repositories {
        [...]
    }
    dependencies {
        classpath "com.malinskiy.marathon:marathon-gradle-plugin:0.6.0"
        classpath "com.malinskiy.marathon:base:0.6.0"
        classpath "com.malinskiy.marathon:core:0.6.0"

        [...]        
    }
}
```

Could a solution be to replace `implementation` with `api` for those modules inside **marathon-gradle-plugin/build.gradle.kts**? I mean:

**marathon-gradle-plugin/build.gradle.kts**
```
    implementation(project(":core"))  <-- Use API to allow import ScreenRecordConfiguration
    implementation(project(":vendor:vendor-android:base")) <-- Use API to allow import Vendor type
```

**Comment by asos-jorgegonzalez** [comment]
I defined the Marathon stuff in the file `buildscript` in one single file:

**root/app/build.gradle**
```
buildscript{
    repositories{
        google()
        mavenCentral()
        maven { url 'https://dl.bintray.com/qameta/maven' }
        gradlePluginPortal()
    }
    dependencies{
        classpath "com.malinskiy.marathon:marathon-gradle-plugin:0.6.0"
        classpath "com.malinskiy.marathon:base:0.6.0"
        classpath "com.malinskiy.marathon:core:0.6.0"
    }
}

apply plugin: 'marathon'

marathon {
    vendor = com.malinskiy.marathon.android.VendorType.ADAM
    [...]
}
```

The plugin is working properly but vendor option doesn't work. This is the error
`Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'ADAM' with class 'com.malinskiy.marathon.android.VendorType' to class 'com.malinskiy.marathon.android.VendorType'`

**Comment by Malinskiy** [comment]
I've tried to reproduce your problem and failed. https://github.com/Malinskiy/marathon/tree/test/440

This correctly recognizes the adam module and executes the tests:
https://github.com/Malinskiy/marathon/blob/test/440/sample/android-app/app/build.gradle#L28

I'm not sure where you are applying the plugin, but it definitely shouldn't be the root gradle. Wherever you apply the application/library android plugin - the marathon apply block should be also there.

Also you don't need
```
        classpath "com.malinskiy.marathon:base:0.6.0"
        classpath "com.malinskiy.marathon:core:0.6.0"
```
This should be picked up by gradle automatically

**Comment by asos-jorgegonzalez** [comment]
The issue is solved for com.malinskiy.marathon.android.VendorType.ADAM from an import perspective. I was importing in my app/build.gradle another gradle file with the marathon configuration. Then I was using apply from: 'myMarathonConfig.gradle' to import the config. Now I moved everything into app/build.gradle and that works. Thanks.
 

Now I am having the issue with `ScreenshotConfiguration`. I can import it because gradle can print the class, I mean:
```
println com.malinskiy.marathon.android.ScreenshotConfiguration
output = class com.malinskiy.marathon.android.ScreenshotConfiguration
```
But if I try to build the object it fail. Example
```
com.malinskiy.marathon.android.ScreenshotConfiguration()
output = Could not get unknown property 'com' for project ':app' of type org.gradle.api.Project. // ERROR
```

Do you know how can I build the object?

Thanks

---- EDIT ----
In addition, I tried to instantiate the `ScreenshotConfiguration` using `ObjectFactory` and I got this error:

```
ObjectFactory objectFactory = rootProject.services.get(ObjectFactory)
objectFactory.newInstance(com.malinskiy.marathon.android.ScreenshotConfiguration,
true, 1080, 1920,200)

Output:
A problem occurred evaluating project ':app'.
> Could not create an instance of type com.malinskiy.marathon.android.ScreenshotConfiguration.
   > Class ScreenshotConfiguration is final.
```

---- EDIT ----
I achieved to instantiate the `ScreenshotConfiguration` using the method `newInstance()`. Now everything is working as expected. Thanks and good job :D

**Comment by Malinskiy** [comment]
@asos-jorgegonzalez glad you've found a way, but a small reminder that you don't need to gradle's internal object factory with reflection to instantiate classes in Groovy, simple `new` is enough:

```
marathon {
    screenRecordConfiguration = new ScreenRecordConfiguration(
        com.malinskiy.marathon.device.DeviceFeature.SCREENSHOT,
        new VideoConfiguration(
            false, //enabled
            1080, //width
            1920, //height
            2, //Bitrate in Mbps
            300, //Max duration in seconds
            TimeUnit.SECONDS
        ),
        new ScreenshotConfiguration(
            false, //enabled
            1080, //width
            1920, //height
            200 //Delay between taking screenshots
        )
    )
}
```

https://github.com/Malinskiy/marathon/blob/test/440/sample/android-app/app/build.gradle#L34

Cheers
