### ISSUE TITLE
Migrate CLI to Clikt

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#450]
**Is your feature request related to a problem? Please describe.**
Looks like https://github.com/xenomachina/kotlin-argparser is not actively maintained. Only two commits since 18 Aug 2018.

**Describe the solution you'd like**
Migrate to https://github.com/ajalt/clikt/
Clikt provides more features and better supported

**Describe alternatives you've considered**
https://github.com/Kotlin/kotlinx-cli is another option, but situation is similar to https://github.com/xenomachina/kotlin-argparser

**Comment by SergKhram** [comment]
@tagantroy close it, pls, because of done
