### ISSUE TITLE
Report paths are possibly incompatible with windows

### ISSUE THREAD

**Issue by trevjonez** [MarathonLabs/marathon#465]
**Describe the bug**
The file names for devices when using tcp to connect to emulators contain colons `:` 
Colons are not a legal character on windows for file names. So better unzip tools such as 7zip will replace them with underscore making the unzip process work fine, but then all the link URL's with colons are invalid.

**To Reproduce**
create a report with a device that has a colon in its name on a *nix based system
zip the report up
unzip the report on a windows machine with 7zip or likely any other advanced archive tool (windows built in extract fails to finish at all)
try to navigate into the report and the links are broken as a result of being sanitized

**Expected behavior**
Report file structure would be safely portable to different file systems.

**Logs and reports**
N/A

**Devices (please complete the following information):**
N/A

**Additional context**
I would expect some basic name sanitizing when generating the report would resolve this in a fairly simple way.

**Comment by Malinskiy** [comment]
This should not be an issue in 0.7.0 since the paths go through escaping for anything besides alphanumeric values. I believe it worked fine in a VM last time I checked this

**Comment by GodArtGithub** [comment]
bug repruduce in version 0.7.0

Logs:
[0;39mmarathon v0.7.0: Test run finished
Exception in thread "Thread-3" java.io.FileNotFoundException: ...\app\build\reports\marathon\debugAndroidTest\devices\omni\127.0.0.1:5037:26d6ca78.json (The filename, directory name, or volume label syntax is incorrect)

**Comment by Malinskiy** [comment]
Seems like the the device serial number is not escaped there, I’ll check and get back to you
