### ISSUE TITLE
Mp4 videos turned into gif

### ISSUE THREAD

**Issue by stMayhem** [MarathonLabs/marathon#468]
After updating the marathon plugin from version 0.5.2 to 0.6.1 the video is now recorded as a GIF. How to make it again mp4?

**Comment by Malinskiy** [comment]
Hey @stMayhem 

Can you provide all the info in https://github.com/Malinskiy/marathon/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md that was requested?

Thanks

**Comment by stMayhem** [comment]
Sorry for the long answer. Unfortunately I can't attach the logs from my main project, since it is under NDA. But I took your [example](https://github.com/Malinskiy/marathon/tree/develop/sample/android-app) from the repository and reproduced the bug.
STR: 
1. Change the marathon version to 0.6.1
2. Make the one of the MainActivityTest test always fall.
3. (optional) Add to allow list          `add(com.malinskiy.marathon.execution.SimpleClassnameFilter("MainActivityTest*".toRegex()))`
4. Run ./gradlew marathon

Here are the logs:
[reports.zip](https://github.com/Malinskiy/marathon/files/6108482/reports.zip)
Expected behavior: Video is present in mp4 format

Device: Emulator (API 28)

**Comment by Malinskiy** [comment]
I agree there is a problem with the priority of recording types, but you can still change it with `preferableRecorderType` https://malinskiy.github.io/marathon/ven/android.html#screen-recorder-configuration for the existing versions

**Comment by stMayhem** [comment]
Thank you for the answer. In addition, the default GIF output does not look very good. It seems to me that it is worth limiting the size of the container.
![image](https://user-images.githubusercontent.com/16138832/110599340-cded7900-8193-11eb-8cda-d169868b772c.png)

**Comment by Malinskiy** [comment]
I welcome your feedback, but I'd also appreciate if issues are not mixed together under one. It makes it very hard to track them.

Thanks!
