### ISSUE TITLE
Clear /data/local/tmp/ device folder after marathon run

### ISSUE THREAD

**Issue by sundetova** [MarathonLabs/marathon#476]
**Is your feature request related to a problem? Please describe.**
Device's storage is being filled up because folder /data/local/tmp/ is not cleaned after test running.

**Describe the solution you'd like**
Clean tmp storage after marathon running and after trying to install apk to device.

**Comment by Malinskiy** [comment]
Hey @sundetova 

I remember this being an issue only for ddmlib. Adam currently [clears apks](https://github.com/Malinskiy/marathon/blob/develop/vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamAndroidDevice.kt#L275)

Is there anything besides apks that you want marathon to delete?

**Comment by deliain** [comment]
Hi there, 
we are also experiencing the problem that our devices' running our tests runs, their storage is getting full because of saving the videos where the test case failed. 
Are there any news to this topic?  Is there a way with marathon to clean the storage after some time? or even before starting the next test run?

**Comment by Malinskiy** [comment]
@deliain could you please show a list of files that are taking the space? I need to understand what to include in the cleanup logic. Originally this issue was about the apks that are taking up the space

**Comment by deliain** [comment]
we investigated a little bit, and in some devices we saw that the videos generated by marathon on failure were saved on the device storage,  directly in the "Internal Storage" folder or in some cases in a temporary folder called "test" and they were not deleted after some time. So far, I did not experience that behavior anymore. Not sure if that was a one time problem but as right now looks better on our devices connected to the servers.

**Comment by Malinskiy** [comment]
For the videos, the cleanup is definitely happening: https://github.com/MarathonLabs/marathon/blob/066b73f456e8ff809396db4a44e413dfa456a24a/vendor/vendor-android/base/src/main/kotlin/com/malinskiy/marathon/android/executor/listeners/video/ScreenRecorderTestBatchListener.kt#L116

I'm close the issue, please reopen if the problem persists
