### ISSUE TITLE
AnnotationDataFilter doesn't work:  java.util.NoSuchElementException: Key value is missing in the map.

### ISSUE THREAD

**Issue by zuevasasha78** [MarathonLabs/marathon#478]
https://github.com/Malinskiy/marathon/blob/0ad0a92f6b0bcb890d9c56c3dbe80e3ecd7d87ba/core/src/main/kotlin/com/malinskiy/marathon/execution/Filter.kt#L100

Поправьте на values.getOrDefault. Сейчас сборка падает так как не у все аннотация есть  value

**Comment by Malinskiy** [comment]
Hey @zuevasasha78 

As far as I understand the issue, using the `AnnotationDataFilter` in your use-case leads to an exception that `value` field is missing.

Why would you filter using `AnnotationDataFilter` instead of `AnnotationFilter` for annotation that does not contain any value?

**Comment by tagantroy** [comment]
@Malinskiy I think it is actually a bug.  Fixed in #485

**Comment by tagantroy** [comment]
Fixed
