### ISSUE TITLE
Introduce merge blocking validatePlugins check

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#482]
**Is your feature request related to a problem? Please describe.**
We have no integration testing for gradle plugin, I think it would be nice to have at least validatePlugins job.

**Describe the solution you'd like**
run `./gradlew validatePlugins` on diffs

**Additional context**
Validates plugins by checking property annotations on work items like tasks and artifact transforms. This task should be used in Gradle plugin projects for doing static analysis on the plugin classes. The java-gradle-plugin adds a validatePlugins task, though if you cannot use this plugin then you need to register the task yourself. See the user guide for more information on incremental build and caching task outputs.

**Comment by Malinskiy** [comment]
@tagantroy pr is merged, do we need to close the issue?

**Comment by tagantroy** [comment]
> @tagantroy pr is merged, do we need to close the issue?

We can close it.
