### ISSUE TITLE
Silence "Pulling into" log output

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#494]
It seems that I get the same seven lines of logging after nearly every test:

Pulling into /\<snip>/build/reports/marathon/device-files/omni/screenshots
Pulling into /\<snip>/build/reports/marathon/device-files/allure-results
Pulling into /\<snip>/build/reports/marathon/device-files/omni/coverage
Pulling into /\<snip>/build/reports/marathon/device-files/allure-results
Pulling into /\<snip>/build/reports/marathon/device-files/omni/coverage
Pulling into /\<snip>/build/reports/marathon/device-files/allure-results
Pulling into /\<snip>/build/reports/marathon/device-files/omni/coverage

This drastically increases the log output, which I would like to avoid. I would like a way to turn these off so they don't clog my logs. Something as simple as "verboseLogging: false" may be adequate.

On a separate note, I'm wondering if it's necessary to do this after every test rather than waiting until the end, and what sort of effect that has on speed. But for the sake of this FR, I'm happy enough if I can just reduce the log size.

**Comment by Malinskiy** [comment]
Thanks for reporting the issue. Should be behind the debug flag now after #495 gets merged
