### ISSUE TITLE
Missing videos for incomplete tests

### ISSUE THREAD

**Issue by hram** [MarathonLabs/marathon#497]
**Describe the bug**
If incomplete tests are present I'd like to investigate the failure and see a video

**To Reproduce**
Steps to reproduce the behaviour:
1. Use `screenRecordingPolicy: "ON_ANY"`
2. Disable retries `retryStrategy:  type: "no-retry"`
3. Have a test that will finish as incomplete
4. Incomplete incomplete test retries regardless of `retryStrategy`
5. After successful execution video file is rewritten by successful execution
6. Unable to investigate the reason of incomplete state of test during the 1st execution

**Expected behavior**
Report should contain videos for incomplete tests

**Comment by Malinskiy** [comment]
Changes in #508 should address this and provide a screen capture at the end of a failed test batch if the device still appears to be healthy. The naming of the file will be the batch UUID.

**Comment by Malinskiy** [comment]
Released in 0.6.2
Feel free to reopen if you'd like to add anything
