### ISSUE TITLE
Documentation search is broken

### ISSUE THREAD

**Issue by sphanley** [MarathonLabs/marathon#505]
The search function on the [marathon documentation](https://marathonlabs.github.io/marathon/) was broken by the migration to the `https://marathonlabs.github.io/` URL. When you type in a search term and try to click on any result, it still tries to take you to the `https://malinskiy.github.io/` URL.

**Comment by Malinskiy** [comment]
I've sent a request to Algolia team to fix this, will reply back here once I have something

**Comment by Malinskiy** [comment]
@sphanley should be resolved now
