### ISSUE TITLE
Hardcoded iframe height in HTML Report Timeline

### ISSUE THREAD

**Issue by VictorIreri** [MarathonLabs/marathon#511]
**Is your feature request related to a problem? Please describe.**
The HTML Report Timeline on the homepage has a relatively small height that only allows enough room to see 3 devices at a time. If tests ran on more than 3 devices it's a bit annoying to have to scroll up and down in such a small section. Furthermore, the header in the timeline is part of the scrollable view so you lose that information when you scroll.
![marathon partial timeline](https://user-images.githubusercontent.com/20208034/120128397-c7cacf80-c1b9-11eb-8305-b11bd5f82957.png)

I noticed the iframe height is hardcoded to a value of "137". Why is that?
https://github.com/MarathonLabs/marathon/blob/5964ce78feb90c785b46ff44b1718f782c77d9b4/html-report/src/components/HomePage.js#L52

**Describe the solution you'd like**
- It would be nice if the iframe height could expand to fit the content so I can see numerous devices and scrolling would only be required if the content didn't fit on the screen.
  - Or the iframe could always take up the full height of the screen.
  - Or the iframe hardcoded height value could be increased.
- Removing the Execution timeline header content from the scrollable section would be nice too.

![marathon full timeline](https://user-images.githubusercontent.com/20208034/120128411-cdc0b080-c1b9-11eb-8ad2-6518855607a8.png)

**Describe alternatives you've considered**
Currently using the TamperMonkey Chrome extension to run this little bit of javascript automatically when I open the page.
`document.getElementsByTagName("iframe")[0].style="width: 100%; height: 500px;";`

**Additional context**
Perhaps this will be useful in implementing a solution.
https://stackoverflow.com/questions/5867985/full-screen-iframe-with-a-height-of-100

**Comment by Malinskiy** [comment]
Hey @VictorIreri
Thanks for reporting the issue.

I see how this can be frustrating to use. Would you be able to create a PR with a change? I'm not sure any particular hardcoded height will be enough because there will always be more devices than expected by the height, so the only reasonable solution is to actually place this content into the main report

**Comment by VictorIreri** [comment]
Hey @Malinskiy 
Not quite my expertise, unfortunately. 
Hopefully it'll be trivial for someone with more experience in this.

**Comment by Malinskiy** [comment]
@VictorIreri I'm not a frontend dev, but I gave this a fair shot in #698 :sweat_smile:
