### ISSUE TITLE
Homebrew support - Apple silicon

### ISSUE THREAD

**Issue by trevjonez** [MarathonLabs/marathon#540]
I've yet to dig into why and what options there are, but the dependency to `openjdk@8` seems to block use of the tap. Manually download release obviously works fine.

![image](https://user-images.githubusercontent.com/5386503/126000737-6767860f-7965-4478-8df1-a559773f002a.png)

SEO: This is on the Apple M1 MacBook macOS 11.4

**Comment by Malinskiy** [comment]
Hey @trevjonez 
I think this issue should be resolved by updating the https://github.com/Malinskiy/homebrew-tap/blob/master/Formula/marathon.rb#L9 to opendk 11. Unfortunately, I don't have access to a device with Apple's silicon and hence am unable to test the change. Would you be able to test it out and submit a PR to https://github.com/Malinskiy/homebrew-tap?
Thanks!
