### ISSUE TITLE
The Report is not getting generated ,  Test run failed with java.lang.reflect.InaccessibleObjectException exception

### ISSUE THREAD

**Issue by dilip-tc** [MarathonLabs/marathon#552]
Marathon 0.6.4

got the same issue as #548 , so upgraded Marathon from Marathon 0.6.2 to Marathon 0.6.4

Initially tried to run the sample app https://github.com/MarathonLabs/marathon/tree/develop/sample/android-app  with the following marathon File, the test run failed with the java.lang.reflect.InaccessibleObjectException  Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @2eb231a6

then ran Other project with similar marathon file using Marathon 0.6.4 , test run failed with same exception 

**Logs and reports**
[fullLog.txt](https://github.com/MarathonLabs/marathon/files/7108511/fullLog.txt)
[marathonFile.txt](https://github.com/MarathonLabs/marathon/files/7108512/marathonFile.txt)
[output.zip](https://github.com/MarathonLabs/marathon/files/7108518/output.zip)

**Devices :**
 - Device: Oneplus
 - OS: Android 11

**Comment by Malinskiy** [comment]
Hey @dilip-tc. Thanks for submitting the issue.
Can you please provide your JRE version?

**Comment by Malinskiy** [comment]
Upstream issue: https://github.com/google/gson/issues/1875

**Comment by dilip-tc** [comment]
yes @Malinskiy , having JRE version "1.8.0_152"

**Comment by Malinskiy** [comment]
Is that Oracle jre or something else?

**Comment by dilip-tc** [comment]
yes @Malinskiy , it is Oracle jre
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_152-b16
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_152
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.152-b16
    os.arch = x86_64
    os.name = Mac OS X
    os.version = 10.15.7

**Comment by Malinskiy** [comment]
@dilip-tc would you be able to verify if https://github.com/MarathonLabs/marathon/pull/553 fixes your issue?
there is also additional logging now in debug mode during the start of the test run to double-check which version of JRE you are using

**Comment by dilip-tc** [comment]
yes @Malinskiy  #553 fixes the issue , report is being generated without exception and the device-files is also being pulled ,
Thanks for the fixing the issue so quickly

**Comment by Malinskiy** [comment]
No worries at all. I'll close this issue when the PR is merged. Cheers
