### ISSUE TITLE
No coverage files with Android 11 / API 30

### ISSUE THREAD

**Issue by simonpoole** [MarathonLabs/marathon#565]
**Describe the bug**
No coverage files are written on Android 11 / API 30 (this is relevant as from next month on this is the required target sdk for distribution on the play store).

For the avoidance of doubt: contrary to previous Android versions the files are not written to the _coverage_ directory that marathon creates. It isn't an issue with the files not being pulled.

**To Reproduce**
The build and the test configuration target Android 11 / API 30, adam vendor variant, gradle plugin 0.6.5. Run against stock emulator x86 / API 30.

Configuration

```
marathon {
    uncompletedTestRetryQuota = 1
    poolingStrategy {
        operatingSystem = true
    }
    // uncommenting this makes things slower, but potentially less flaky
//    applicationPmClear = true
    codeCoverageEnabled = true
    autoGrantPermission = true
    vendor = com.malinskiy.marathon.android.VendorType.ADAM
    retryStrategy {
        fixedQuota {
            retryPerTestQuota = 2
            totalAllowedRetryQuota = 100
        }
    }
    // uncomment for running specific tests
    filteringConfiguration {
        allowlist = [
            new com.malinskiy.marathon.execution.filter.FullyQualifiedTestnameFilter(null,
               [
                    'de.blau.android.tasks.ReadSaveTasksTest#readAndSaveCustomBugs'
               ], 
               null)
        ]
    }
}
```

**Expected behavior**
Coverage files are generated and pulled to the host.

**Logs and reports**
Attached for Android 11 and as a comparison the same from a parallel run on Android 10.

The relevant bit is however likely

```
10-06 07:06:13.339 1519-5549/? E/MediaProvider: insertFileIfNecessary failed
10-06 07:06:13.339 1519-5549/? E/MediaProvider: java.lang.IllegalArgumentException: Primary directory coverage not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2682)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2347)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2957)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3486)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3208)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:6655)
10-06 07:06:13.339 1519-5549/? E/MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:6742)
10-06 07:06:13.340 5408-5408/? D/SavingHelper: save thread finished
```

**Devices (please complete the following information):**
 - stock emulator x86 
 - Android 11 / API 30

**Additional context**

The log would indicate that the issue is due to the more restrictive handling of file access in Android 11, and likely could be avoided by creating the coverage file directory in Download/coverage instead of in /sdcard (but no guarantee :-)), this should work on all previous Android versions too.

[android11-de.blau.android.tasks.ReadSaveTasksTest#readAndSaveCustomBugs-d2e85a05-a3a8-44a4-a168-d2aa14d4f9fb.log](https://github.com/MarathonLabs/marathon/files/7291608/android11-de.blau.android.tasks.ReadSaveTasksTest.readAndSaveCustomBugs-d2e85a05-a3a8-44a4-a168-d2aa14d4f9fb.log)
[android10-de.blau.android.tasks.ReadSaveTasksTest#readAndSaveCustomBugs-6e9cba78-d60b-445b-b9a0-29b8d2d73f86.log](https://github.com/MarathonLabs/marathon/files/7291614/android10-de.blau.android.tasks.ReadSaveTasksTest.readAndSaveCustomBugs-6e9cba78-d60b-445b-b9a0-29b8d2d73f86.log)

**Comment by Malinskiy** [comment]
Can you please follow the permissions advice in https://marathonlabs.github.io/marathon/ven/android.html#syncpull-files-from-device-after-test-run and see if that helps?

**Comment by simonpoole** [comment]
I have that set, see https://github.com/MarcusWolschon/osmeditor4android/blob/android11/src/androidTest/AndroidManifest.xml

Investigating a bit further, post running the test it seems as if the permission wasn't granted (the marathon log however claims it was), see:

![Screenshot_1633514487](https://user-images.githubusercontent.com/1011860/136182734-e0c49235-88d1-4085-b8e7-a28934025051.png)

**Comment by simonpoole** [comment]
Further data point, granting the permission via adb to the test app via the package manager does not actually work,:

```
adb shell pm grant de.blau.android.test android.permission.MANAGE_EXTERNAL_STORAGE

Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.MANAGE_EXTERNAL_STORAGE requested by de.blau.android.test is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:451) ...
```

according to https://developer.android.com/training/data-storage/manage-all-files#enable-manage-external-storage-for-testing 
and irl

```
 adb shell appops set --uid de.blau.android.test MANAGE_EXTERNAL_STORAGE allow
```

works.

**Comment by Malinskiy** [comment]
The grant of this permission happens exactly like this:
https://github.com/MarathonLabs/marathon/blob/develop/vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AndroidDeviceTestRunner.kt#L141

Can you please attach the execution log rather than logcat please? :)

**Comment by simonpoole** [comment]
> 
> 
> The grant of this permission happens exactly like this: https://github.com/MarathonLabs/marathon/blob/develop/vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AndroidDeviceTestRunner.kt#L141

I was just going to correct myself and point out that that looks right, but see below. 
> 
> Can you please attach the execution log rather than logcat please? :)

The log always indicated that the permission was granted. But the actual problem is something completely else, and is partly a documentation issue.

The instructions say _Starting with Android 11 your test application will require MANAGE_EXTERNAL_STORAGE permission:_ that is confusing terminology because that is the package_name.test app, not the app that is being tested. I requested the permission for the test app and not for the actual app itself. as the instructions could be interpreted as requiring. 

Requesting the permission for the app itself does lead to the coverage files being generated (just tested now), but that leads to the issue (besides having to create a separate manifest for the debug version as asking for the permission in the release manifest is a big nono), that we end up not testing the stock app and not being able to detect any file permission issues (which is the major point of testing against Android 11 to start with). With other words, writing the coverage files to an app specific directory that it is allowed to access would be the far better solution.

**Comment by Malinskiy** [comment]
Yes, you have to grant this permission to the application under test: it's process is doing the write operations AFAIK.

Looking at the logs of the execution I also found
```
java.io.FileNotFoundException: /storage/emulated/0/Download/Vespucci/autopreset/autopreset.xml: open failed: EACCES (Permission denied)
```
Might also need the same permission for other reasons.

Anyways :+1:

**Comment by simonpoole** [comment]
> java.io.FileNotFoundException: /storage/emulated/0/Download/Vespucci/autopreset/autopreset.xml: open failed: EACCES (Permission denied)

That's the problem, if the MANAGE_EXTERNAL_STORAGE is granted you can't detect such an error any more.
