### ISSUE TITLE
Could not get unknown property 'AggregationMode' for extension 'marathon'

### ISSUE THREAD

**Issue by alirezaafkar** [MarathonLabs/marathon#579]
According to the docs, for pulling files form device I use this configuration in gradle(groovy)

```
fileSyncConfiguration {
        pull.add(
                FileSyncEntry(
                        "Pictures",
                        AggregationMode.POOL
                )
        )
    }
```

and build fails with this exception:

`Could not get unknown property 'AggregationMode' for extension 'marathon' of type com.malinskiy.marathon.MarathonExtension.`

What is wrong in my configuration?

- marathon version: 0.6.5
- gradle version: 7.2

**Comment by Malinskiy** [comment]
Aggregation mode is an enum, you need an import statement at the top of your file or use the FQDN

**Comment by alirezaafkar** [comment]
I tried this:
` com.malinskiy.marathon.config.vendor.android.AggregationMode.POOL`

and this:
`com.malinskiy.marathon.android.configuration.AggregationMode.POOL`

and didn't work.

` Could not get unknown property 'com' for extension 'marathon' of type com.malinskiy.marathon.MarathonExtension.`

**Comment by Malinskiy** [comment]
For 0.6.5 the configuration for file sync is in the `com.malinskiy.marathon.android.configuration` package (https://github.com/MarathonLabs/marathon/blob/0.6.5/vendor/vendor-android/base/src/main/kotlin/com/malinskiy/marathon/android/configuration/FileSyncConfiguration.kt)

```
marathon {
    fileSyncConfiguration {
        pull.add(
            com.malinskiy.marathon.android.configuration.FileSyncEntry(
                "Pictures",
                com.malinskiy.marathon.android.configuration.AggregationMode.POOL
            )
        )
    }
}
```

Can you please try using the FQDN above and see if it fixes the problem?

**Comment by alirezaafkar** [comment]
Nope, Should I use kotlin script? I use groovy.

**Comment by Malinskiy** [comment]
With the example above did the error message change?

I would try switching to kts if I was you.

 In the meantime I can try reproducing the Groove configuration.

**Comment by alirezaafkar** [comment]
error message still is `Could not get unknown property 'com' for extension 'marathon' of type com.malinskiy.marathon.MarathonExtension.`

**Comment by Malinskiy** [comment]
I got so used to Kotlin that I missed the `new` for calling constructor in Groovy:

```
marathon {
    fileSyncConfiguration {
        pull.add(new com.malinskiy.marathon.android.configuration.FileSyncEntry("Pictures", com.malinskiy.marathon.android.configuration.AggregationMode.POOL))
    }
}
```

**Comment by alirezaafkar** [comment]
Worked :)) Thanks.
