### ISSUE TITLE
Feature Request: Standalone marathon yml file generation task

### ISSUE THREAD

**Issue by trevjonez** [MarathonLabs/marathon#589]
**Is your feature request related to a problem? Please describe.**
Currently our CI setup generates a marathon file via a bash heredoc setup, that config is then packaged with apk's and sent to an external system for execution.

Being able to utilize the gradle DSL to replace the bash scripting could be a big win for developer UX when running locally as the marathon file would become dynamic and on demand while also letting me capture the configuration in more of a "single source of truth" model.

**Describe the solution you'd like**
Split the [MarathonRunTask](https://github.com/MarathonLabs/marathon/blob/develop/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/gradle/MarathonRunTask.kt) into a generate config task and a run task. Looking at the existing task logic it is likely there would need to be a few things modified in order to do adhoc generate config tasks, but the existing logic is 99% of the way there, just needs to be decoupled a bit more.

**Describe alternatives you've considered**
As mentioned a heredoc pattern is being used in bash scripts which is fine for CI, but really leaves any local marathon runs as a fairly tedious process for developers that are new to the tool.

Anything I can do to help people avoid manually writing YML I'd like to pursue :laughing:

**Comment by Malinskiy** [comment]
Closed by #701
