### ISSUE TITLE
Please publish sources jar

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#600]
Would love to be able to directly view source code/docs in Android Studio

For android subprojects (requires AGP 7.1): https://developer.android.com/studio/releases/gradle-plugin#publish-javadoc-jar
For jvm subprojects: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example

**Comment by Malinskiy** [comment]
We publish the sources as this is a requirement from maven central to upload any release. E.g. https://repo1.maven.org/maven2/com/malinskiy/marathon/core/0.7.0/

Can you please be more specific with the problem, e.g. module that doesn’t have sources?

**Comment by ZakTaccardi** [comment]
Actually I don't know what changed but I'm now getting sources correctly through Android Studio! My bad

**Comment by ZakTaccardi** [comment]
I think what may have somehow contributed to this was that I originally was missing the `:configuration` artifact as its a runtime dependency of `-gradle-plugin` - so both needed to be declared

```kts
// in `buildSrc/build.gradle.kts`
implementation("com.malinskiy.marathon:marathon-gradle-plugin:0.7.0")
implementation("com.malinskiy.marathon:configuration:0.7.0")
```

In https://repo1.maven.org/maven2/com/malinskiy/marathon/marathon-gradle-plugin/0.7.0/marathon-gradle-plugin-0.7.0.pom

```xml
<dependency>
<groupId>com.malinskiy.marathon</groupId>
<artifactId>configuration</artifactId>
<version>0.7.0</version>
<scope>runtime</scope>
</dependency>
```

You may want that one to be a `compile` dependency

**Comment by Malinskiy** [comment]
It is an `implementation` dependency in the code, no idea how it transformed into a runtime one tbh

https://github.com/MarathonLabs/marathon/blob/develop/marathon-gradle-plugin/build.gradle.kts#L31
