### ISSUE TITLE
Time to start tests is slow compared to Spoon/AGP

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#601]
The time between initial task execution when `marathonDebugAndroidTest` begins and the first test begins executing is quite slow.

I have a project with 8 empty android tests. For fully cached builds (when everything has already been built), I tested with Marathon, Spoon, and connectedAndroidTest. Here were my results:

```kts
:logging:marathonDebugAndroidTest // 53.932s
:logging:spoonDebugAndroidTest // 17.512s
:logging:connectedAndroidTest // 8.378s
```

There seems to be a significant delay (30+ seconds) when `:marathonDebugAndroidTest` begins its execution and when it actually starts executing the first test.

Any idea what is causing the delay/how we could reduce it?

**Comment by tagantroy** [comment]
Hi @ZakTaccardi, could you create sample project to help us reproduce and profile this issue?

**Comment by ZakTaccardi** [comment]
sure! will take some time to create a shareable reproducer, but I can hopefully get one to you in a few days.

**Comment by Malinskiy** [comment]
By the way, is this problem related to the first execution or any subsequent execution as well?
The reason for the question is the CLI is cached locally after the first execution and should be very quickly reused on the next test run. Unless you changed the version of the Gradle plugin.

**Comment by ZakTaccardi** [comment]
the first execution took an incredibly long time (prob something to do with resource fetching). Prob related to my work's VPN. So much so that I thought the marathon task was just hanging. Follow up executions where much quicker, but still significantly slower compared to Spoon/AGP, and why I filed this issue.

Does marathon cache the install of the APK? If the APK is already installed - no need to re-install IMO

**Comment by Malinskiy** [comment]
@ZakTaccardi can you please be a bit specific with ‘increadibly long’? Did you measure the first execution? Please provide the log with timestamps.

Marathon extracts everything from a local file so it doesn’t depend on your internet connection. Did you try to use CLI to compare the performance?

To answer your second question: no, marathon doesn’t cache installation of the APK and never will: reason being there is no way to understand if what you have installed is the correct version to test. This is to minimise side-effects and possible mistakes with same apk version but different code.

**Comment by ZakTaccardi** [comment]
I want to chalk this up to some weird enterprise/work laptop security setting, because now Spoon tests are slow too
