### ISSUE TITLE
Marathon script fails if apk file contains brackets

### ISSUE THREAD

**Issue by stMayhem** [MarathonLabs/marathon#613]
Marathon script fails if testing apk file contains brackets.
**STR**:

1. Name the file so that the name includes brackets. For example: test(1).apk.
For this In _android.defaultConfig_ section of app level _build.gradle.kts_ add:
`setProperty("archivesBaseName", "test(1)")`
4. Run `./gradlew marathon`
5. See error in console: `com.malinskiy.adam.exception.RequestRejectedException: Unexpected exit code value pected '('`

Marathon version: **0.7.0**

**Expected behaviour:**
Escape brackets in apk file name.

**Comment by Malinskiy** [comment]
@stMayhem thanks for reporting this, will be fixed for adam in the 0.7.2
