### ISSUE TITLE
Marathon creates a test ID per test. Can I access it at test runtime to display screenshots in the marathon report?

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#615]
Marathon generates a file like:

```
marathon/debugAndroidTest/screenshot/omni/127.0.0.1-5037-emulator-5554/component-ui.LandingComponentUiTest#land-29ba1e65-b2ec-4dc2-b016-66b2b5645a01.gif
```

As far as I know, marathon does not directly support taking screenshots during tests (I don't really understand what `RecorderType.SCREENSHOT` does as AFAIK Marathon has no hooks to actually take multiple screenshots during test time), so I need to somehow rework AndroidX's `ScreenCaptureProcessor` to scope its screenshots to Marathon. Given that the file above seems to havea test ID of `29ba1e65-b2ec-4dc2-b016-66b2b5645a01` - how do I feed this info to test code at runtime so I can correctly tag each AndroidX screenshot with the right test ID? Is this possible?

I'd love to be able to communicate to Marathon - here are the screenshots I took with AndroidX's `ScreenCaptureProcessor` ([docs](https://developer.android.com/reference/androidx/test/runner/screenshot/ScreenCaptureProcessor)) during a test run, please display them (in order) alongside the video in the marathon report. Is this possible?

Note: this is the marathon config I used for `FileSyncEntry` to pull the screenshots taken during a test with AndroidX's Screenshot API, which uses `BasicScreenCaptureProcessor` ([docs](https://developer.android.com/reference/androidx/test/runner/screenshot/BasicScreenCaptureProcessor)) by default.

```
marathon {
    screenRecordingPolicy = ScreenRecordingPolicy.ON_ANY

    fileSyncConfiguration = FileSyncConfiguration(
        pull = mutableListOf(
            FileSyncEntry(
                aggregationMode = AggregationMode.TEST_RUN,
                // This is where AndroidX's `BasicScreenCaptureProcessor` puts their pictures. Works on API 30 (have not tested others)
                relativePath = "Pictures/screenshots/"
            ),
        )
    )
}
```

**Comment by Malinskiy** [comment]
#682 adds support for test runtime screen captures that are automatically collected via marathon. Will be released in the next version
The screencaptures are visible via Allure's report

The UUID you see in the log is not a test case id, it's the batch UUID as in a unique identifier of a group of tests. If you still need this id for other reasons - please open another issue.

Thanks
