### ISSUE TITLE
Allure reports not generating after upgrading allure version from 2.8.1 to 2.9.4 with Marathon library

### ISSUE THREAD

**Issue by sonamkuk** [MarathonLabs/marathon#616]
I am working on generating allure reports with Marathon library for my Espresso automation test to embedd screenshots in the report. The test reports were generating fine with screenshots for below configuration
Allure-gradle @2.8.1
Marathon-gradle plugin @0.6.2
Gradle 6.0

Since we migrated to Gradle 7.0 and we had open issues of multiple getters with allure-gradle version 2.8.1, so I upgraded allure-gradle version from 2.8.1 to 2.9.4 but I was not able to make this reports generate with current configuration. When tried with running it with warning mode -  ./gradlew allureReport --warning-mode=all
I am getting below error:

![image](https://user-images.githubusercontent.com/5415879/157313585-f1b43c49-2292-4729-b117-e1156c71c57d.png)

 Resolution of the configuration :**allureRawResultDirs** was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. See 

allure-results are generating under marathon reports but allure reports are not getting generated

I am using below configuration:
allure {
  report {
    version.set("2.13.9")
    reportDir.file(project.rootDir.absolutePath+"/app/build/reports/allure-report")
  }
}
allure-gradle version 2.9.4 with Junit4

**Comment by Malinskiy** [comment]
Hey @sonamkuk. Thanks for submitting this issue. Could you please explain why this particular problem is an issue with marathon? The output directory for the report is bound to the current module in gradle by default, so if you have a `:app` module your json files for the report will be in `./app/build/reports/marathon`. How you generate report from the actual data is out of scope for marathon and I’m not sure how I can help here. Maybe you can file an issue with the allure gradle plugin?

**Comment by Malinskiy** [comment]
@sonamkuk please close the issue if there is nothing else here :)

**Comment by Malinskiy** [comment]
Closing, feel free to reopen if there is something on the marathon's side of this
