### ISSUE TITLE
Install extra applications

### ISSUE THREAD

**Issue by kavabunga6** [MarathonLabs/marathon#629]
**Is your feature request related to a problem? Please describe.**
When we use black box tests we need install 3 apk:
- main app
- main app contains test classes (other repository)
- test app (other repository)

**Describe the solution you'd like**
Allow to specify a list extra apk for install on device

EXAMPLE FOR MARATHONFILE:

```
extraApplicationsApk: 
    - "app/build/outputs/apk/androidTest/debug/extra.apk"
    - "app/build/outputs/apk/androidTest/debug/extra_two.apk"
```

**Comment by Malinskiy** [comment]
Closed by #630
