### ISSUE TITLE
Push files before each test

### ISSUE THREAD

**Issue by kavabunga6** [MarathonLabs/marathon#646]
**Problem**
Some tests require special resources which should not be stored in assets (binary files, specified files for current run)

**Solution**
Add option for push files to device before each test
For first iteration we can add everything in **/data/local/tmp/marathon**

**Example 1**
![example](https://user-images.githubusercontent.com/9674794/168566716-16522419-950c-4b6f-855b-0ec462b9a5e5.png)

**Comment by Malinskiy** [comment]
Closed via #648
