### ISSUE TITLE
How to execute tests only on specific Android device(N devices are connected locally)?

### ISSUE THREAD

**Issue by neestell** [MarathonLabs/marathon#667]
Hello!
Is there a way to run tests using device id/uuid or any other identifier?
I have N devices connected to macbook. For a configuration "A" tests must be executed on device id 1, for a configuration "B" tests must be executed on device id 2.

Thank you!

**Comment by Malinskiy** [comment]
Hey @neestell, thanks for raising this.

You can filter out devices using the `includeSerialRegexes` and `excludeSerialRegexes` to filter out devices based on their serial numbers. In your case you just need to specify `id 1` and `id 2` as a regex for includeSerialRegexes, that should be enough.

**Comment by neestell** [comment]
Thanks! Works as expected
