### ISSUE TITLE
Unsupported new AGP versions 7.2.2+

### ISSUE THREAD

**Issue by FasdAR** [MarathonLabs/marathon#679]
**Describe the bug**
If use the agp version higher `7.0.3` and the plugin version `0.7.4` get an error at the moment of sync project:
```
Unable to find method ''com.android.build.api.component.AndroidTest com.android.build.api.variant.ApplicationVariant.getAndroidTest()''
'com.android.build.api.component.AndroidTest com.android.build.api.variant.ApplicationVariant.getAndroidTest()'
```

The version agp on which i get error: `7.2.2`
If use the agp version as in the simples `7.0.3` then this error disappears

The gradle version use - `7.4`

**To Reproduce**
Steps to reproduce the behaviour:
1. Use `id("marathon") version "0.7.4"`
2. Use the agp version 7.2.2

**Expected behavior**
No error

**Logs and reports**
[Log Gist](https://gist.github.com/FasdAR/d275263ef62fa330b6a4b30a99c61eaa)

**Comment by Malinskiy** [comment]
Someone can't resist moving packages around: https://cs.android.com/android-studio/platform/tools/base/+/18db44f3e7e51643a0010084706d39dd9dab27a9
