### ISSUE TITLE
Can not start test without --no-window-animation key

### ISSUE THREAD

**Issue by sergey2att** [MarathonLabs/marathon#681]
Hi guys
I am using marathon configuration with ADAM and it looks like it is impossible to start a test without --no-window-animation
```
D 16:42:38.674 [AndroidDevice - execution - 127.0.0.1:5037:10.8.0.200:7481-2 @coroutine#175] <AndroidDeviceTestRunner> Running 00F2shell:am instrument -w -r --no-window-animation -e class com.project.tests.smartTV.OrderFoodOverviewPageTest#testOverview com.project..test/io.qameta.allure.android.runners.AllureAndroidJUnitRunner
I 16:42:52.675 [AndroidDevice - execution - 127.0.0.1:5037:10.8.0.200:7481-1 @coroutine#175] <DebugTestRunListener> testRunStarted 127.0.0.1:5037:10.8.0.200:7481
```
I don't use any additional instrument parameters in marathon configuration file. And it would be great to have no-window-animation as optional.

**Comment by Malinskiy** [comment]
Hey @sergey2at, thanks for the issue!

Can you please elaborate why you would like to wait for the window animation? Are you testing the window animations?

Thanks

**Comment by sergey2att** [comment]
Hi Anton! 
In my case disabling animation broke some functionality with widgets. I can't modify code of developers, that is why for me using animation is only way for testing and I would happy to have ability to manage window animation.
