### ISSUE TITLE
emulator changed state to NOTHING_TO_DO

### ISSUE THREAD

**Issue by Syne10** [MarathonLabs/marathon#708]
After the update marathon, the logs began to get clogged with similar warnings:
`[DeviceMonitor @coroutine#6] <AdamDeviceProvider> Device [MASKED]:6006 changed state to NOTHING_TO_DO`

please tell me why this might be happening?

**Comment by Malinskiy** [comment]
Because your device is changing the state in the adb server, e.g  OFFLINE -> AUTHORIZING

Under normal circumstances this shouldn't happen during the run unless you dynamically connect devices

**Comment by Malinskiy** [comment]
Closing since this is not an issue related to marathon. If you don't want to see these logs - disable the debug mode.
