### ISSUE TITLE
New release with commons-text-1.10

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#714]
The newest release does not include the security patched version of the library commons-text. 1.9 had a security issue, and 1.10 was merged into develop recently, so all we need is a new release.

**Comment by stMayhem** [comment]
https://seclists.org/oss-sec/2022/q4/22

**Comment by Malinskiy** [comment]
The next release is going to take some time since it includes several breaking changes.
In the meantime the above vulnerability should not have any security risk unless the attack vector of submitting a random `Marathonfile`s  applies to you.
I will update this issue closer to the `0.8.0`

**Comment by sphanley** [comment]
Plausible attack vector or not, my team is about to have to go through a bunch of paperwork to request an enterprise security variance to continue using Marathon with this known vulnerability past our normal remediation window. Is there any possibility of getting a 0.7.7 release which is simply 0.7.6 with the commons-text version bumped? Barring that, do you have any tentative expectation of when the next release is likely, so we can use it in our internal variance request?

**Comment by Malinskiy** [comment]
Released in 0.8.0
