### ISSUE TITLE
[Android] Tests parse directory

### ISSUE THREAD

**Issue by neestell** [MarathonLabs/marathon#717]
Hello!
I have a project with two modules: app(application) and tests(android.test). Marathon and test files are in test module(`src/main/java`). .**apk**  and androidTest.**apk** are in an app module.
When I try to run test via _marathon_ a result is `NoTestCasesFoundException: No tests cases were found`. 
How to set tests' source parse directory?
Thanks

**Comment by Malinskiy** [comment]
Hey @neestell, please provide your `Marathonfile` as well as the full output of running `marathon`.

Seems like you didn't configure the run correctly.

**Comment by neestell** [comment]
If I put test files in `app/src/androidTest` all works as expected
```
name: "sample-app tests"
outputDir: "build/reports/marathon"
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 2
vendorConfiguration:
  type: "Android"
  applicationApk: "../../build/outputs/apk/devGoogle/debug/app-dev-debug.apk"
  testApplicationApk: "../../build/outputs/apk/androidTest/devGoogle/debug/app-dev-debug-androidTest.apk"
  autoGrantPermission: true
  instrumentationArgs:
    debug: "true"
  applicationPmClear: false
  testApplicationPmClear: false
  vendor: ADAM
  timeoutConfiguration:
    # ISO_8601 duration
    install: "P1DT12H30M5S"
  waitForDevicesTimeoutMillis: 60000
  allureConfiguration:
    enabled: true
    relativeResultsDirectory: "/allure-results"
  screenRecordConfiguration:
    preferableRecorderType: "screenshot"
    videoConfiguration:
      enabled: false
      width: 1080
      height: 1920
      bitrateMbps: 2
      timeLimit: 300
    screenshotConfiguration:
      enabled: false
      width: 1080
      height: 1920
      delayMs: 200
deviceInitializationTimeoutMillis: 180000
filteringConfiguration:
  allowlist:
    - type: "simple-class-name"
      regex: "AuthUserTest"
    - type: "method"
      regex: "shouldPassOnOffline_mock"
```

**Comment by Malinskiy** [comment]
I'm not sure what is _it_ in your sentence, but I suspect you're having trouble with paths. Here is a snippet from the documentation that might help:

> When specifying relative host file paths in the configuration they will be resolved relative to the directory of the Marathonfile, e.g. if you have /home/user/app/Marathonfile with baseOutputDir = "./output" then the actual path to the output directory will be /home/user/app/output.

The test source files are not used by marathon in any way. The only files that are used are the 2 apk files you specify here:
```yaml
applicationApk: "../../build/outputs/apk/devGoogle/debug/app-dev-debug.apk"
testApplicationApk: "../../build/outputs/apk/androidTest/devGoogle/debug/app-dev-debug-androidTest.apk"
```

From what you described above, it seems like you've put source files for tests in a directory that is not picked up by your build system hence the resulting `app-dev-debug-androidTest.apk` didn't contain any tests.

**Comment by neestell** [comment]
You are right! Probably `app-dev-debug-androidTest.apk` does not contains test files because of a build system misconfigured for tests in a separate module. 
Thanks!
