### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by Malinskiy** [MarathonLabs/marathon#729]
**Is your feature request related to a problem? Please describe.**
Users get confused with the documentation since it's built from develop and it might contain changes that are not yet released. It's also hard to see the docs for a previous version of marathon.

**Describe the solution you'd like**
Dropdown menu for the version

**Describe alternatives you've considered**
None

**Additional context**
Suggestion to use https://docusaurus.io/docs/versioning

**Comment by ildar2** [comment]
It's weird that official doc says "Marathon gradle plugin is published as an official Gradle plugin since version 0.8.0", but the latest version I could find is 0.7.6

**Comment by Malinskiy** [comment]
That is precisely why this ticket exists
