### ISSUE TITLE
Broken docs.marathonlabs.io

### ISSUE THREAD

**Issue by TuMoH** [MarathonLabs/marathon#732]
https://docs.marathonlabs.io/doc/configuration.html shows Page not found

**Comment by austyh** [comment]
Fixed. 404 pages will be redirected to the main.

**Comment by Malinskiy** [comment]
We've just released the new versioned docs, so the urls changed a bit. A redirect to home should guide you to the required content.

Closing the issue.

**Comment by TuMoH** [comment]
I can't open the "Options" page

https://user-images.githubusercontent.com/9692299/212703915-2f400fbf-d264-4216-832d-769e0355be24.mov

**Comment by Malinskiy** [comment]
What you're showing is the old version of docs. Please cleanup your cache in the browser or force reload the page (shift f5 in chrome-based browsers).

**Comment by TuMoH** [comment]
Oh, thank you!
I'm a simple user and could not have guessed it =)

**Comment by Malinskiy** [comment]
No worries at all. 
Sorry for breaking this stuff: our new versioned docs should help access content of pages regardless of the new releases and give you ability to look on previous versions, so broken links shouldn’t be an issue for a number of years from this point forward.
