### ISSUE TITLE
Docs: A few typos & grammatical errors

### ISSUE THREAD

**Issue by VictorIreri** [MarathonLabs/marathon#759]
I spotted a few minor typos & grammatical errors in the docs. I can create a PR if you're happy with these proposed changes.

occurance -> occurrence
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/configuration/dynamic-configuration.md?plain=1#L12

---

want to the build -> want the build
failed use -> failed, use
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L153
implementation code -> implementation, code
by user -> by the user
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L184-L185
This parameter specifies that the underlying test executor should time out if there is no test output within this duration.
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L217
This parameter specifies that the underlying test executor should time out if the batch execution exceeds this duration.
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L250
run starts device -> run starts, the device
to be changed please -> to be changed, please
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L283-L284
is used for we're -> is used for, we're
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L315
Enabled -> Enables
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L412
By default, screen recording will -> By default, screen recordings will
save screen recording regardless -> save screen recordings regardless
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L443-L445
due to some of OSs limitations -> due to limitations of some OSs
limit it's user's -> limit, it's the user's
set it up to larger value if OS -> set a larger value if the OS
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/intro/configure.md?plain=1#L477-L479

---
Multi module -> Multi-module
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L89
version less Android 5 -> versions below Android 5
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L122
to customise -> customisation of
Sequantially -> Sequentially
non empty -> non-empty
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L265
marshmallow -> Marshmallow
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L275
device -> the device
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L310
Configuration -> The configuration
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L481
that is usually the `/sdcard/` on most of the devices -> which is usually `/sdcard/` on most devices
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L520-L521
needs -> needs the
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L568
under -> under the
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L585
this marathon -> this, marathon
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L640
This is power-user feature -> This is a power-user feature
GPS location -> GPS locations
thanks to the access to device-under-test -> thanks to access to the device-under-test
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L912-L913
for description -> for a description
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L918-L919
Default configuration of marathon -> The default configuration
assumes that adb server -> assumes that the adb server
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L953
Adb server -> Adb servers
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L960
marathon uses -> marathon uses the
https://github.com/MarathonLabs/marathon/blob/48c3c9f700b55dd7fda5880a51e010c034ff819d/docs/docs/android/configure.md?plain=1#L1068

**Comment by VictorIreri** [comment]
I guess this is an enhancement, not a bug, but I can't change the label.

**Comment by Malinskiy** [comment]
Spot on! :rocket:
