### ISSUE TITLE
Docs: Latest changes to docs are not searchable

### ISSUE THREAD

**Issue by VictorIreri** [MarathonLabs/marathon#764]
Searching for text that was recently added to the docs yields no results.
For example, the new "Fast execution mode" added [here](https://github.com/MarathonLabs/marathon/pull/758/commits/162926da7aa14bbe2b161c152fa43eb10b3f20e1) can't be found. However, "Strict mode" was removed but is still searchable.
Something to do with the Algolia crawler? Or maybe something about supporting 2 versions of documentation (`develop` & `0.7.6`) isn't working well? I haven't checked but perhaps all changes in `develop` would not be reflected in search.

<img src=https://user-images.githubusercontent.com/20208034/223545528-7c669c9a-df25-4f07-bdc8-704d14c88ee8.png width="400" />
<img src=https://user-images.githubusercontent.com/20208034/223549203-f3b11609-32a9-4832-803c-d37c4e5f3e19.png width="400" />

**Comment by Malinskiy** [comment]
Algolia's crawler is triggered weekly every Thursday. This is expected.

**Comment by VictorIreri** [comment]
Can I ask why on Thursdays? 🤔  Why not on every push to develop? (Or every push to develop that changes the `docs` folder?) Is that within your control and is there an associated cost?
