### ISSUE TITLE
Launching single class UI test

### ISSUE THREAD

**Issue by atetc** [MarathonLabs/marathon#8]
It's feature request: consider to add the possibility to launch single UI test class (with several tests) from terminal/console

It's important for development/debugging

P.S. IDE plugin also could be good option in the future.

**Comment by dsvoronin** [comment]
Why do you need marathon for that?
Looks like a simple case for embedded IDE runner/debugger, and emulator on host machine

**Comment by Malinskiy** [comment]
Addressed by #34

**Comment by Malinskiy** [comment]
Released in 0.1.3
