### ISSUE TITLE
Is there a way to disable bugsnag when running Marathon from gradle?

### ISSUE THREAD

**Issue by tabletenniser** [MarathonLabs/marathon#818]
The https://docs.marathonlabs.io/intro/execute/ doc only includes instructions on how to disable `bugsnag` when running Marathon from CLI. Is there a way to disable it when running it via gradle?  Quick look in the Marathon documentation didn't find me any.

**Comment by Malinskiy** [comment]
I though it was behind https://docs.marathonlabs.io/intro/configure#analytics-tracking but looking at the code it doesn't seem to be.

You can generate the marathonfile view gradle and call the CLI with bugsnag disabled.

What's the issue with bugsnag?

**Comment by tabletenniser** [comment]
Thanks, I tried setting the following in my `app/build.gradle.kts`:
```
marathon {
  name = "Instrumentation Tests"
  analyticsTracking = false
...
}
```
but still seeing the following in log:
```
> Task :app:marathonPlayDebugAndroidTest
14:57:08.549 [main] INFO  c.m.marathon.cli.ApplicationView - Starting marathon v0.8.2, CliConfiguration: MarathonRunCommandCliConfiguration(marathonfile=/Users/aaronwang/Duolingo/duolingo-android/app/build/marathon/playDebugAndroidTest/Marathonfile, analyticsTracking=true, bugsnagReporting=true)
``` 

Does that mean the analyticsTracking is applied after that line gets logged?

> You can generate the marathonfile view gradle and call the CLI with bugsnag disabled.
Yes, but the reason we use gradle instead of Marathon CLI directly is so that we can have a single gradle command to do app APK build, test APK build and test execution all in one command for local development. Generating Marathon file from gradle and call it via Marathon CLI deviates this purpose. For CI/CD, we already call Marathon CLI with bugsnag disabled.

> What's the issue with bugsnag?
I think not sending data to bugsnag is a requirement from our security team.

**Comment by Malinskiy** [comment]
Okay, sounds like something we want to add. Happy to review a PR with this change.

**Comment by tabletenniser** [comment]
Drafted https://github.com/MarathonLabs/marathon/pull/820 for this. Two quick questions:
1) Pointers on any integration / unit tests I should add for that?  I tested it working end-to-end using `samples/android-app`. But feel free to suggest any integration / unit tests I should add for it.
2) What's the release cadence of our gradle repo?  After the PR gets merged, is there any process I should follow so that https://plugins.gradle.org/plugin/com.malinskiy.marathon gets updated?

Thanks!

**Comment by Malinskiy** [comment]
1. There are no tests for gradle-specific tests for configuration, but there are ones for Configuration and for ConfigurationFactory [here](https://github.com/MarathonLabs/marathon/tree/develop/configuration/src/test/kotlin/com/malinskiy/marathon/config/serialization).  I feel like at least one test fixture can be added there with tracking disabled.
2. Releases are bundled together and are triggered by the presence of a git tag. a CLI version is released and gradle plugin is published. I'll do this sometime after the PR gets merged

**Comment by Malinskiy** [comment]
Release in 0.8.4
