### ISSUE TITLE
Erroneous $ in flakiness overhead string

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#825]
**Describe the bug**
There's a random $ hanging out at the end of this string:
Flakiness overhead: 0H 01m 00s$

**To Reproduce**
Steps to reproduce the behaviour:
Just run 0.8.3 and look at the logs at the end for flakiness overhead

**Expected behavior**
Should look like this instead:
Flakiness overhead: 0H 01m 00s

**Additional context**
Here is my comically small commit on my fork, though I won't be offended if you don't use it:
https://github.com/Progressive-Insurance/marathon/commit/1934a9a677e323c98cc4b79cbab51743d3841676

**Comment by Malinskiy** [comment]
Raised in #826

**Comment by Malinskiy** [comment]
In develop, will be release once the new version if ready
