### ISSUE TITLE
Running tests parallel

### ISSUE THREAD

**Issue by neestell** [MarathonLabs/marathon#842]
Hello, Anton!
I cannot find a sample or a doc to run tests in parallel using 2+ computers(connected with N devices) in one local network.  Does this feature exists? For example, I have 4 tests, 4 devices connected to 2 computers. Every test should be run once on any device. If it does, please clarify how to reach it.
Thank you

**Comment by Malinskiy** [comment]
You probably missed https://docs.marathonlabs.io/android

The mode you're referring to is the default mode (i.e. an omni pool and no sharding strategy)

**Comment by Malinskiy** [comment]
Also to clarify: you can connect your devices to as many hosts as you need. The only requirement there is that they expose devices via adb or have direct access to adb server

**Comment by neestell** [comment]
Thank you
