### ISSUE TITLE
Since 0.9.0 testClassRegexes is removed, test class filtering stops working

### ISSUE THREAD

**Issue by floppydrive6** [MarathonLabs/marathon#870]
**Describe the bug**
Before 0.9.0 I used `testClassRegexes` config property (Gradle plugin) to filter out test classes which should be executed (based on file name regex), do you know how we can achieve pretty the same (using Gradle plugin) in version 0.9.0?

I found in changelog that it was [removed](https://github.com/MarathonLabs/marathon/pull/851) and moved to iOS configuration only, but it seemed to be working for Android as well (<0.9.0), and now I wonder how I can easily replace it?

Not sure if it should be achieved with: `testParserConfiguration`? If so, do you have some examples using Gradle plugin how it can be done? 
Thanks in advance for any suggestions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Full configuration
2. Any additional information about the device provider (devices that were stuck, etc.)

**Expected behavior**

**Logs and reports**
Add an execution log to help explain your problem. If possible, provide the report folder.

**Devices (please complete the following information):**
 - Device: [e.g. emulator/simulator/Nexus 5/etc]

**Additional context**

**Comment by Malinskiy** [comment]
Duplicate of #865
Please migrate to using [filtering](https://docs.marathonlabs.io/runner/configuration/filtering/)

**Comment by Malinskiy** [comment]
The most direct drop-in replacement would be
```
filteringConfiguration:
  allowlist:
    - type: "fully-qualified-class-name"
      regex: "com\.example\.SomeClassTest.*"
```

**Comment by floppydrive6** [comment]
thanks a lot, I will migrate to filteringConfiguration then, closing issue! 😄
