### ISSUE TITLE
Console stdout points analyticsTracking and bugsnagReporting = true even when they are set to false in marathonfile. 

### ISSUE THREAD

**Issue by kartik1o** [MarathonLabs/marathon#904]
**Describe the bug**
Console logs: analyticsTracking and bugsnagReporting = true even when they are set to false in marathonfile. 
` INFO  c.m.marathon.cli.ApplicationView - Starting marathon v0.9.1, CliConfiguration: MarathonRunCommandCliConfiguration(marathonfile=**/app/build/marathon/debugAndroidTest/Marathonfile, analyticsTracking=true, bugsnagReporting=true)`

**To Reproduce**
apply marathon gradle plugin in the application module of your project.
in the app-level build.gradle file, configure marathon block, and set bugsnagReporting and analyticsTracking to false.
```
marathon {
bugsnagReporting = false
analyticsTracking = false
}
```
or create marathonfile manually and run `marathon` command in console.

**Expected behavior**
These properties should be false in this case. 

**Logs and reports**
Add an execution log to help explain your problem. If possible, provide the report folder.

**Devices (please complete the following information):**
Not relevant

**Additional context**

**Comment by Malinskiy** [comment]
What you're seeing are the command-line flag overrides set to true. Gradle configuration is fully mapped to a generated Marathonfile, you can check it

```yaml
...
analyticsTracking: false
bugsnagReporting: false
...
```

There are multiple ways to disable analytics, see https://github.com/MarathonLabs/marathon/blob/1fc058b2f10c6897ed887fac705c623278c22220/configuration/src/main/kotlin/com/malinskiy/marathon/config/serialization/ConfigurationFactory.kt#L112 for how it works.

There is no functional problem here. If you want to improve the printout to stdout - feel free to submit a PR.
