### ISSUE TITLE
Parse annotation values

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#93]
2.0.0 dex parser lib support annotation values.
We should add support for values too, because it can be useful for some cases.

**Comment by cdsap** [comment]
what's the use case for annotation values?

**Comment by dsvoronin** [comment]
for example add custom filtration logic: skip some tests based on annotation values, it could be min/max sdk

**Comment by tagantroy** [comment]
https://github.com/Malinskiy/marathon/blob/7ed64d9c72fe5eccd0f8f9791266ba42f8ddff27/core/src/main/kotlin/com/malinskiy/marathon/test/MetaProperty.kt
