### ISSUE TITLE
[Android] Test passed, but Marathon reported it as stuck and gave an incomplete result.

### ISSUE THREAD

**Issue by akexorcist** [MarathonLabs/marathon#978]
**Describe the bug**
I'm having a problem where some tests pass and the Android device continues to work normally, but Marathon says the test got stuck and gave the result as 'incomplete'. This causes the test case to be retried on a different Android device. Sometimes it passes after one retry, but sometimes it takes more than 10 retries, which makes the test run take a long time.

Here are some details about the system I'm working with:
* Running 60+ end-to-end test cases
* Running on Android emulators in the cloud
* Each test run uses 4-8 Android emulators
* Tests are written using Kaspresso and Kakao

Here is my Marathon configuration file.

```
name: "Android E2E Test"
outputDir: "marathon-report"
poolingStrategy:
    type: "omni"
batchingStrategy:
    type: "isolate"
retryStrategy:
    type: "fixed-quota"
    totalAllowedRetryQuota: 50
    retryPerTestQuota: 1
debug: true
uncompletedTestRetryQuota: 2
outputConfiguration:
    maxPath: 1024
filteringConfiguration:
    allowlist:
    - type: "composition"
      filters:
      - type: "annotation"
        regex: ".*LargeTest"
      - type: "fully-qualified-class-name"
        regex: ${SPECIFIC_FQCN_REGEX}
      - type: "simple-class-name"
        regex: '^((?!Abstract).)*Test'
      op: "INTERSECTION"
vendorConfiguration:
    type: "Android"
    applicationApk: "build/apks/app.apk"
    testApplicationApk: "build/apks/app-androidTest.apk"
    allureConfiguration:
        enabled: true
    serialStrategy: "ddms"
    applicationPmClear: true
    testApplicationPmClear: true
```

**To Reproduce**
I don't know how to reproduce this issue. From what I've observed, it seems to happen randomly. Sometimes there's no problem, and sometimes there is. 

**Expected behavior**
Test should pass when it actually pass.

**Logs and reports**
![image](https://github.com/user-attachments/assets/abd4159b-41a2-4fbb-ba2b-0d9f80e3416a)

From the image above, You can see that Kaspresso indicates the test passed

![image](https://github.com/user-attachments/assets/c9aabfbc-2752-42de-b45e-b4eb19f1b0c9)

But Marathon says "Test got stuck. You can increase the timeout in settings if it's too strict" then got incomplete test result. This causes Marathon to try to re-run this test on other devices in the device pool (most recently, I saw this happen in a loop about 10 times).

**Devices (please complete the following information):**
 - Device: Android Emulator (Genymotion Device Image)
 - OS: Android 13
 - Marathon CLI v0.10.1

**Additional context**
N/A

**Comment by akexorcist** [comment]
My workaround is to add more time for `testBatchTimeoutMillis` and `testOutputTimeoutMillis`

```
testBatchTimeoutMillis: 5400000
testOutputTimeoutMillis: 600000
```

**Comment by Malinskiy** [comment]
Hey @akexorcist
This is expected behaviour: if your test succeeds outside of the allocated timeframe then it is considered uncompleted and eventually failed. Tests should be small enough so that they can be parallelized for execution. As you've found configuring marathon to support long tests is one of the solutions. A better one is to rework your test code.

Cheers
